program test.aleo{
	fn main(  a
	        :  u64  )  ->  u64   {
            if  a  >  5u64  {  return
                1u64  ;  }
    if a  <  3u64
	{
                    return
                        2u64  ;
        }
if a  ==  4u64  {  return 3u64  ;  }  else  {  return
        4u64  ;  }
	    if a  >10u64{
            return 5u64
                ;
    }  else
                if a  >  7u64
	{  return
	    6u64  ;  }
            else  {
    return 7u64
        ;
        }
    }
}
