/*
namespace: ParseStatement
expectation: Fail
*/

x.-12

x.0_;

x.0_0;

x.01;

x.0_.

x.0_import

x.0_,

x.0_*

x.0_+

x.0_-

x.0_/

x.0_[

x.0_]

x.0_{

x.0_}

x.0_(

x.0_)

x.0_:

x.0_::

x.0_?

x.0__

x.0_=

x.0_==

x.0_!

x.0_!=

x.0_>

x.0_>=

x.0_<

x.0_<=

x.0_>

x.0_..

x.0_as

x.0_console

x.0_const

x.0_let

x.0_for

x.0_if

x.0_else

x.0_i8

x.0_i16

x.0_i32

x.0_i64

x.0_i128

x.0_u8

x.0_u16

x.0_u32

x.0_u64

x.0_u128

x.0_&

x.0_return

x.0_self

x.0_Self

x.0_true

x.0_false

