#!/usr/bin/env bash

LEO_BIN=${1}

PROG="'extra_prog'"
NET="'aleo'"
FUNC="'dbl'"
INPUT="7u64"

echo "--- run WITHOUT --with should fail ---"
${LEO_BIN} run main ${PROG} ${NET} ${FUNC} ${INPUT} 2>&1 || true

echo "--- run WITH --with should succeed ---"
${LEO_BIN} run main ${PROG} ${NET} ${FUNC} ${INPUT} --with ./extra_prog.aleo

echo "--- run a standalone Aleo file ---"
${LEO_BIN} --path ./extra_prog.aleo run dbl ${INPUT}

echo "--- write standalone Aleo run JSON output ---"
${LEO_BIN} --path ./extra_prog.aleo --json-output run dbl ${INPUT}
cat ./build/json-outputs/run.json
rm ./build/json-outputs/run.json

exit 0
