/*
namespace: ParseStatement
expectation: Pass
*/

let x: u8 = expr;

let x: u16 = x+y;

let x: u8 = x();

let x: string = expr;


const x: i8 = expr;

const x: i16 = x+y;

const x: i8 = x();

const x: string = expr;


let x: u32 = expr;

let x: u32 = x+y;

let x: u32 = x();


const x: u32 = expr;

const x: u32 = x+y;

const x: u32 = x();

let x: address = aleo1fj982yqchhy973kz7e9jk6er7t6qd6jm9anplnlprem507w6lv9spwvfxx;
