/*
namespace: ParseStatement
expectation: Pass
*/

let x: u8 = expr;

let x: u16 = x+y;

let x: u8 = x();

let x: string = expr;


const x: i8 = expr;

const x: i16 = x+y;

const x: i8 = x();

const x: string = expr;


let x: u32 = expr;

let x: u32 = x+y;

let x: u32 = x();


const x: u32 = expr;

const x: u32 = x+y;

const x: u32 = x();

let x: address = aleo15u4r0gzjtqzepkgurgn7p3u5kkhs9p74rx6aun3uh2s5std6759svgmg53;
