
let x = expr;

let x = ();

let x = x+y;

let x = (x,y);

let x = x();


const x = expr;

const x = ();

const x = x+y;

const x = (x,y);

const x = x();


let x: u32 = expr;

let x: u32 = ();

let x: u32 = x+y;

let x: u32 = (x,y);

let x: u32 = x();


const x: u32 = expr;

const x: u32 = ();

const x: u32 = x+y;

const x: u32 = (x,y);

const x: u32 = x();


let (x,y,,) = ();

let (,x,y) = ();

let (x,,y) = ();

let x: [u8; (2,,)] = [[0,0], [0,0]];


let x: const = expr;

const x: let = expr;

let

let x

let x:

let x = (a, y]);

let = 1u8;

let;

let x 1u8;

let x: u8;

let x: u8

let x: = 1;

let x: [u8] = 1;

let x: [u8;

let x: [u8; 1u8] = [1,

let dbg: u8 = ];

let 🦀: u8 = 0;

let (x) = ...;

let (x,) = ...;

let _1: u8 = 1u8;

let 1___091: u8 = 12u8;
