// Copyright (C) 2019-2025 Provable Inc.
// This file is part of the Leo library.

// The Leo library is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// The Leo library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with the Leo library. If not, see <https://www.gnu.org/licenses/>.

use leo_span::{Symbol, sym};

use snarkvm::prelude::LiteralType;
use snarkvm::synthesizer::program::{CommitVariant, ECDSAVerifyVariant, HashVariant};

/// A core instruction that maps directly to an AVM bytecode instruction.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CoreFunction {
    // ChaCha random value of type (LiteralType).
    ChaChaRand(LiteralType),
    // Commitment to a value using hash (HashVariant) returning value of type (LiteralType).
    Commit(CommitVariant, LiteralType),
    // ECDSA verify with hash (HashVariant) and the ETH variant (bool).
    ECDSAVerify(ECDSAVerifyVariant),
    // Hash function with variant (HashVariant) returning value of type (LiteralType).
    Hash(HashVariant, LiteralType),

    MappingGet,
    MappingGetOrUse,
    MappingSet,
    MappingRemove,
    MappingContains,

    GroupToXCoordinate,
    GroupToYCoordinate,

    // Schnorr signature verification with raw (bool) bytes.
    SignatureVerify(bool),

    FutureAwait,

    ProgramChecksum,
    ProgramEdition,
    ProgramOwner,

    CheatCodePrintMapping,
    CheatCodeSetBlockHeight,
}

impl CoreFunction {
    /// Returns a `CoreFunction` from the given module and method symbols.
    #[rustfmt::skip]
    pub fn from_symbols(module: Symbol, function: Symbol) -> Option<Self> {
        Some(match (module, function) {
            (sym::ChaCha, sym::rand_address) => Self::ChaChaRand(LiteralType::Address),
            (sym::ChaCha, sym::rand_bool)    => Self::ChaChaRand(LiteralType::Boolean),
            (sym::ChaCha, sym::rand_field)   => Self::ChaChaRand(LiteralType::Field),
            (sym::ChaCha, sym::rand_group)   => Self::ChaChaRand(LiteralType::Group),
            (sym::ChaCha, sym::rand_i8)      => Self::ChaChaRand(LiteralType::I8),
            (sym::ChaCha, sym::rand_i16)     => Self::ChaChaRand(LiteralType::I16),
            (sym::ChaCha, sym::rand_i32)     => Self::ChaChaRand(LiteralType::I32),
            (sym::ChaCha, sym::rand_i64)     => Self::ChaChaRand(LiteralType::I64),
            (sym::ChaCha, sym::rand_i128)    => Self::ChaChaRand(LiteralType::I128),
            (sym::ChaCha, sym::rand_u8)      => Self::ChaChaRand(LiteralType::U8),
            (sym::ChaCha, sym::rand_u16)     => Self::ChaChaRand(LiteralType::U16),
            (sym::ChaCha, sym::rand_u32)     => Self::ChaChaRand(LiteralType::U32),
            (sym::ChaCha, sym::rand_u64)     => Self::ChaChaRand(LiteralType::U64),
            (sym::ChaCha, sym::rand_u128)    => Self::ChaChaRand(LiteralType::U128),
            (sym::ChaCha, sym::rand_scalar)  => Self::ChaChaRand(LiteralType::Scalar),

            (sym::BHP256, sym::commit_to_address)   => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Address),
            (sym::BHP256, sym::commit_to_field)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Field),
            (sym::BHP256, sym::commit_to_group)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Group),
            (sym::BHP512, sym::commit_to_address)   => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Address),
            (sym::BHP512, sym::commit_to_field)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Field),
            (sym::BHP512, sym::commit_to_group)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Group),
            (sym::BHP768, sym::commit_to_address)   => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Address),
            (sym::BHP768, sym::commit_to_field)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Field),
            (sym::BHP768, sym::commit_to_group)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Group),
            (sym::BHP1024, sym::commit_to_address)   => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Address),
            (sym::BHP1024, sym::commit_to_field)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Field),
            (sym::BHP1024, sym::commit_to_group)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Group),
            (sym::Pedersen64, sym::commit_to_address)   => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Address),
            (sym::Pedersen64, sym::commit_to_field)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Field),
            (sym::Pedersen64, sym::commit_to_group)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Group),
            (sym::Pedersen128, sym::commit_to_address)   => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Address),
            (sym::Pedersen128, sym::commit_to_field)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Field),
            (sym::Pedersen128, sym::commit_to_group)     => Self::Commit(CommitVariant::CommitBHP256, LiteralType::Group),

            (sym::BHP256, sym::hash_to_address)     => Self::Hash(HashVariant::HashBHP256, LiteralType::Address),
            (sym::BHP256, sym::hash_to_field)       => Self::Hash(HashVariant::HashBHP256, LiteralType::Field),
            (sym::BHP256, sym::hash_to_group)       => Self::Hash(HashVariant::HashBHP256, LiteralType::Group),
            (sym::BHP256, sym::hash_to_i8)          => Self::Hash(HashVariant::HashBHP256, LiteralType::I8),
            (sym::BHP256, sym::hash_to_i16)         => Self::Hash(HashVariant::HashBHP256, LiteralType::I16),
            (sym::BHP256, sym::hash_to_i32)         => Self::Hash(HashVariant::HashBHP256, LiteralType::I32),
            (sym::BHP256, sym::hash_to_i64)         => Self::Hash(HashVariant::HashBHP256, LiteralType::I64),
            (sym::BHP256, sym::hash_to_i128)        => Self::Hash(HashVariant::HashBHP256, LiteralType::I128),
            (sym::BHP256, sym::hash_to_u8)          => Self::Hash(HashVariant::HashBHP256, LiteralType::U8),
            (sym::BHP256, sym::hash_to_u16)         => Self::Hash(HashVariant::HashBHP256, LiteralType::U16),
            (sym::BHP256, sym::hash_to_u32)         => Self::Hash(HashVariant::HashBHP256, LiteralType::U32),
            (sym::BHP256, sym::hash_to_u64)         => Self::Hash(HashVariant::HashBHP256, LiteralType::U64),
            (sym::BHP256, sym::hash_to_u128)        => Self::Hash(HashVariant::HashBHP256, LiteralType::U128),
            (sym::BHP256, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashBHP256, LiteralType::Scalar),
            (sym::BHP256, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::Address),
            (sym::BHP256, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::Field),
            (sym::BHP256, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::Group),
            (sym::BHP256, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::I8),
            (sym::BHP256, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::I16),
            (sym::BHP256, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::I32),
            (sym::BHP256, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::I64),
            (sym::BHP256, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::I128),
            (sym::BHP256, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::U8),
            (sym::BHP256, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::U16),
            (sym::BHP256, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::U32),
            (sym::BHP256, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::U64),
            (sym::BHP256, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::U128),
            (sym::BHP256, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashBHP256Raw, LiteralType::Scalar),

            (sym::BHP512, sym::hash_to_address)     => Self::Hash(HashVariant::HashBHP512, LiteralType::Address),
            (sym::BHP512, sym::hash_to_field)       => Self::Hash(HashVariant::HashBHP512, LiteralType::Field),
            (sym::BHP512, sym::hash_to_group)       => Self::Hash(HashVariant::HashBHP512, LiteralType::Group),
            (sym::BHP512, sym::hash_to_i8)          => Self::Hash(HashVariant::HashBHP512, LiteralType::I8),
            (sym::BHP512, sym::hash_to_i16)         => Self::Hash(HashVariant::HashBHP512, LiteralType::I16),
            (sym::BHP512, sym::hash_to_i32)         => Self::Hash(HashVariant::HashBHP512, LiteralType::I32),
            (sym::BHP512, sym::hash_to_i64)         => Self::Hash(HashVariant::HashBHP512, LiteralType::I64),
            (sym::BHP512, sym::hash_to_i128)        => Self::Hash(HashVariant::HashBHP512, LiteralType::I128),
            (sym::BHP512, sym::hash_to_u8)          => Self::Hash(HashVariant::HashBHP512, LiteralType::U8),
            (sym::BHP512, sym::hash_to_u16)         => Self::Hash(HashVariant::HashBHP512, LiteralType::U16),
            (sym::BHP512, sym::hash_to_u32)         => Self::Hash(HashVariant::HashBHP512, LiteralType::U32),
            (sym::BHP512, sym::hash_to_u64)         => Self::Hash(HashVariant::HashBHP512, LiteralType::U64),
            (sym::BHP512, sym::hash_to_u128)        => Self::Hash(HashVariant::HashBHP512, LiteralType::U128),
            (sym::BHP512, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashBHP512, LiteralType::Scalar),
            (sym::BHP512, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::Address),
            (sym::BHP512, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::Field),
            (sym::BHP512, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::Group),
            (sym::BHP512, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::I8),
            (sym::BHP512, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::I16),
            (sym::BHP512, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::I32),
            (sym::BHP512, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::I64),
            (sym::BHP512, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::I128),
            (sym::BHP512, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::U8),
            (sym::BHP512, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::U16),
            (sym::BHP512, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::U32),
            (sym::BHP512, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::U64),
            (sym::BHP512, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::U128),
            (sym::BHP512, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashBHP512Raw, LiteralType::Scalar),

            (sym::BHP768, sym::hash_to_address)     => Self::Hash(HashVariant::HashBHP768, LiteralType::Address),
            (sym::BHP768, sym::hash_to_field)       => Self::Hash(HashVariant::HashBHP768, LiteralType::Field),
            (sym::BHP768, sym::hash_to_group)       => Self::Hash(HashVariant::HashBHP768, LiteralType::Group),
            (sym::BHP768, sym::hash_to_i8)          => Self::Hash(HashVariant::HashBHP768, LiteralType::I8),
            (sym::BHP768, sym::hash_to_i16)         => Self::Hash(HashVariant::HashBHP768, LiteralType::I16),
            (sym::BHP768, sym::hash_to_i32)         => Self::Hash(HashVariant::HashBHP768, LiteralType::I32),
            (sym::BHP768, sym::hash_to_i64)         => Self::Hash(HashVariant::HashBHP768, LiteralType::I64),
            (sym::BHP768, sym::hash_to_i128)        => Self::Hash(HashVariant::HashBHP768, LiteralType::I128),
            (sym::BHP768, sym::hash_to_u8)          => Self::Hash(HashVariant::HashBHP768, LiteralType::U8),
            (sym::BHP768, sym::hash_to_u16)         => Self::Hash(HashVariant::HashBHP768, LiteralType::U16),
            (sym::BHP768, sym::hash_to_u32)         => Self::Hash(HashVariant::HashBHP768, LiteralType::U32),
            (sym::BHP768, sym::hash_to_u64)         => Self::Hash(HashVariant::HashBHP768, LiteralType::U64),
            (sym::BHP768, sym::hash_to_u128)        => Self::Hash(HashVariant::HashBHP768, LiteralType::U128),
            (sym::BHP768, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashBHP768, LiteralType::Scalar),
            (sym::BHP768, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::Address),
            (sym::BHP768, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::Field),
            (sym::BHP768, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::Group),
            (sym::BHP768, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::I8),
            (sym::BHP768, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::I16),
            (sym::BHP768, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::I32),
            (sym::BHP768, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::I64),
            (sym::BHP768, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::I128),
            (sym::BHP768, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::U8),
            (sym::BHP768, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::U16),
            (sym::BHP768, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::U32),
            (sym::BHP768, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::U64),
            (sym::BHP768, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::U128),
            (sym::BHP768, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashBHP768Raw, LiteralType::Scalar),

            (sym::BHP1024, sym::hash_to_address)     => Self::Hash(HashVariant::HashBHP1024, LiteralType::Address),
            (sym::BHP1024, sym::hash_to_field)       => Self::Hash(HashVariant::HashBHP1024, LiteralType::Field),
            (sym::BHP1024, sym::hash_to_group)       => Self::Hash(HashVariant::HashBHP1024, LiteralType::Group),
            (sym::BHP1024, sym::hash_to_i8)          => Self::Hash(HashVariant::HashBHP1024, LiteralType::I8),
            (sym::BHP1024, sym::hash_to_i16)         => Self::Hash(HashVariant::HashBHP1024, LiteralType::I16),
            (sym::BHP1024, sym::hash_to_i32)         => Self::Hash(HashVariant::HashBHP1024, LiteralType::I32),
            (sym::BHP1024, sym::hash_to_i64)         => Self::Hash(HashVariant::HashBHP1024, LiteralType::I64),
            (sym::BHP1024, sym::hash_to_i128)        => Self::Hash(HashVariant::HashBHP1024, LiteralType::I128),
            (sym::BHP1024, sym::hash_to_u8)          => Self::Hash(HashVariant::HashBHP1024, LiteralType::U8),
            (sym::BHP1024, sym::hash_to_u16)         => Self::Hash(HashVariant::HashBHP1024, LiteralType::U16),
            (sym::BHP1024, sym::hash_to_u32)         => Self::Hash(HashVariant::HashBHP1024, LiteralType::U32),
            (sym::BHP1024, sym::hash_to_u64)         => Self::Hash(HashVariant::HashBHP1024, LiteralType::U64),
            (sym::BHP1024, sym::hash_to_u128)        => Self::Hash(HashVariant::HashBHP1024, LiteralType::U128),
            (sym::BHP1024, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashBHP1024, LiteralType::Scalar),
            (sym::BHP1024, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::Address),
            (sym::BHP1024, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::Field),
            (sym::BHP1024, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::Group),
            (sym::BHP1024, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::I8),
            (sym::BHP1024, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::I16),
            (sym::BHP1024, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::I32),
            (sym::BHP1024, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::I64),
            (sym::BHP1024, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::I128),
            (sym::BHP1024, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::U8),
            (sym::BHP1024, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::U16),
            (sym::BHP1024, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::U32),
            (sym::BHP1024, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::U64),
            (sym::BHP1024, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::U128),
            (sym::BHP1024, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashBHP1024Raw, LiteralType::Scalar),

            (sym::Keccak256, sym::hash_to_address)     => Self::Hash(HashVariant::HashKeccak256, LiteralType::Address),
            (sym::Keccak256, sym::hash_to_field)       => Self::Hash(HashVariant::HashKeccak256, LiteralType::Field),
            (sym::Keccak256, sym::hash_to_group)       => Self::Hash(HashVariant::HashKeccak256, LiteralType::Group),
            (sym::Keccak256, sym::hash_to_i8)          => Self::Hash(HashVariant::HashKeccak256, LiteralType::I8),
            (sym::Keccak256, sym::hash_to_i16)         => Self::Hash(HashVariant::HashKeccak256, LiteralType::I16),
            (sym::Keccak256, sym::hash_to_i32)         => Self::Hash(HashVariant::HashKeccak256, LiteralType::I32),
            (sym::Keccak256, sym::hash_to_i64)         => Self::Hash(HashVariant::HashKeccak256, LiteralType::I64),
            (sym::Keccak256, sym::hash_to_i128)        => Self::Hash(HashVariant::HashKeccak256, LiteralType::I128),
            (sym::Keccak256, sym::hash_to_u8)          => Self::Hash(HashVariant::HashKeccak256, LiteralType::U8),
            (sym::Keccak256, sym::hash_to_u16)         => Self::Hash(HashVariant::HashKeccak256, LiteralType::U16),
            (sym::Keccak256, sym::hash_to_u32)         => Self::Hash(HashVariant::HashKeccak256, LiteralType::U32),
            (sym::Keccak256, sym::hash_to_u64)         => Self::Hash(HashVariant::HashKeccak256, LiteralType::U64),
            (sym::Keccak256, sym::hash_to_u128)        => Self::Hash(HashVariant::HashKeccak256, LiteralType::U128),
            (sym::Keccak256, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashKeccak256, LiteralType::Scalar),
            (sym::Keccak256, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::Address),
            (sym::Keccak256, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::Field),
            (sym::Keccak256, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::Group),
            (sym::Keccak256, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::I8),
            (sym::Keccak256, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::I16),
            (sym::Keccak256, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::I32),
            (sym::Keccak256, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::I64),
            (sym::Keccak256, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::I128),
            (sym::Keccak256, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::U8),
            (sym::Keccak256, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::U16),
            (sym::Keccak256, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::U32),
            (sym::Keccak256, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::U64),
            (sym::Keccak256, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::U128),
            (sym::Keccak256, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashKeccak256Raw, LiteralType::Scalar),

            (sym::Keccak384, sym::hash_to_address)     => Self::Hash(HashVariant::HashKeccak384, LiteralType::Address),
            (sym::Keccak384, sym::hash_to_field)       => Self::Hash(HashVariant::HashKeccak384, LiteralType::Field),
            (sym::Keccak384, sym::hash_to_group)       => Self::Hash(HashVariant::HashKeccak384, LiteralType::Group),
            (sym::Keccak384, sym::hash_to_i8)          => Self::Hash(HashVariant::HashKeccak384, LiteralType::I8),
            (sym::Keccak384, sym::hash_to_i16)         => Self::Hash(HashVariant::HashKeccak384, LiteralType::I16),
            (sym::Keccak384, sym::hash_to_i32)         => Self::Hash(HashVariant::HashKeccak384, LiteralType::I32),
            (sym::Keccak384, sym::hash_to_i64)         => Self::Hash(HashVariant::HashKeccak384, LiteralType::I64),
            (sym::Keccak384, sym::hash_to_i128)        => Self::Hash(HashVariant::HashKeccak384, LiteralType::I128),
            (sym::Keccak384, sym::hash_to_u8)          => Self::Hash(HashVariant::HashKeccak384, LiteralType::U8),
            (sym::Keccak384, sym::hash_to_u16)         => Self::Hash(HashVariant::HashKeccak384, LiteralType::U16),
            (sym::Keccak384, sym::hash_to_u32)         => Self::Hash(HashVariant::HashKeccak384, LiteralType::U32),
            (sym::Keccak384, sym::hash_to_u64)         => Self::Hash(HashVariant::HashKeccak384, LiteralType::U64),
            (sym::Keccak384, sym::hash_to_u128)        => Self::Hash(HashVariant::HashKeccak384, LiteralType::U128),
            (sym::Keccak384, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashKeccak384, LiteralType::Scalar),
            (sym::Keccak384, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::Address),
            (sym::Keccak384, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::Field),
            (sym::Keccak384, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::Group),
            (sym::Keccak384, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::I8),
            (sym::Keccak384, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::I16),
            (sym::Keccak384, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::I32),
            (sym::Keccak384, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::I64),
            (sym::Keccak384, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::I128),
            (sym::Keccak384, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::U8),
            (sym::Keccak384, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::U16),
            (sym::Keccak384, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::U32),
            (sym::Keccak384, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::U64),
            (sym::Keccak384, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::U128),
            (sym::Keccak384, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashKeccak384Raw, LiteralType::Scalar),

            (sym::Keccak512, sym::hash_to_address)     => Self::Hash(HashVariant::HashKeccak512, LiteralType::Address),
            (sym::Keccak512, sym::hash_to_field)       => Self::Hash(HashVariant::HashKeccak512, LiteralType::Field),
            (sym::Keccak512, sym::hash_to_group)       => Self::Hash(HashVariant::HashKeccak512, LiteralType::Group),
            (sym::Keccak512, sym::hash_to_i8)          => Self::Hash(HashVariant::HashKeccak512, LiteralType::I8),
            (sym::Keccak512, sym::hash_to_i16)         => Self::Hash(HashVariant::HashKeccak512, LiteralType::I16),
            (sym::Keccak512, sym::hash_to_i32)         => Self::Hash(HashVariant::HashKeccak512, LiteralType::I32),
            (sym::Keccak512, sym::hash_to_i64)         => Self::Hash(HashVariant::HashKeccak512, LiteralType::I64),
            (sym::Keccak512, sym::hash_to_i128)        => Self::Hash(HashVariant::HashKeccak512, LiteralType::I128),
            (sym::Keccak512, sym::hash_to_u8)          => Self::Hash(HashVariant::HashKeccak512, LiteralType::U8),
            (sym::Keccak512, sym::hash_to_u16)         => Self::Hash(HashVariant::HashKeccak512, LiteralType::U16),
            (sym::Keccak512, sym::hash_to_u32)         => Self::Hash(HashVariant::HashKeccak512, LiteralType::U32),
            (sym::Keccak512, sym::hash_to_u64)         => Self::Hash(HashVariant::HashKeccak512, LiteralType::U64),
            (sym::Keccak512, sym::hash_to_u128)        => Self::Hash(HashVariant::HashKeccak512, LiteralType::U128),
            (sym::Keccak512, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashKeccak512, LiteralType::Scalar),
            (sym::Keccak512, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::Address),
            (sym::Keccak512, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::Field),
            (sym::Keccak512, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::Group),
            (sym::Keccak512, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::I8),
            (sym::Keccak512, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::I16),
            (sym::Keccak512, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::I32),
            (sym::Keccak512, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::I64),
            (sym::Keccak512, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::I128),
            (sym::Keccak512, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::U8),
            (sym::Keccak512, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::U16),
            (sym::Keccak512, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::U32),
            (sym::Keccak512, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::U64),
            (sym::Keccak512, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::U128),
            (sym::Keccak512, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashKeccak512Raw, LiteralType::Scalar),

            (sym::Pedersen64, sym::hash_to_address)     => Self::Hash(HashVariant::HashPED64, LiteralType::Address),
            (sym::Pedersen64, sym::hash_to_field)       => Self::Hash(HashVariant::HashPED64, LiteralType::Field),
            (sym::Pedersen64, sym::hash_to_group)       => Self::Hash(HashVariant::HashPED64, LiteralType::Group),
            (sym::Pedersen64, sym::hash_to_i8)          => Self::Hash(HashVariant::HashPED64, LiteralType::I8),
            (sym::Pedersen64, sym::hash_to_i16)         => Self::Hash(HashVariant::HashPED64, LiteralType::I16),
            (sym::Pedersen64, sym::hash_to_i32)         => Self::Hash(HashVariant::HashPED64, LiteralType::I32),
            (sym::Pedersen64, sym::hash_to_i64)         => Self::Hash(HashVariant::HashPED64, LiteralType::I64),
            (sym::Pedersen64, sym::hash_to_i128)        => Self::Hash(HashVariant::HashPED64, LiteralType::I128),
            (sym::Pedersen64, sym::hash_to_u8)          => Self::Hash(HashVariant::HashPED64, LiteralType::U8),
            (sym::Pedersen64, sym::hash_to_u16)         => Self::Hash(HashVariant::HashPED64, LiteralType::U16),
            (sym::Pedersen64, sym::hash_to_u32)         => Self::Hash(HashVariant::HashPED64, LiteralType::U32),
            (sym::Pedersen64, sym::hash_to_u64)         => Self::Hash(HashVariant::HashPED64, LiteralType::U64),
            (sym::Pedersen64, sym::hash_to_u128)        => Self::Hash(HashVariant::HashPED64, LiteralType::U128),
            (sym::Pedersen64, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashPED64, LiteralType::Scalar),
            (sym::Pedersen64, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashPED64Raw, LiteralType::Address),
            (sym::Pedersen64, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashPED64Raw, LiteralType::Field),
            (sym::Pedersen64, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashPED64Raw, LiteralType::Group),
            (sym::Pedersen64, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashPED64Raw, LiteralType::I8),
            (sym::Pedersen64, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashPED64Raw, LiteralType::I16),
            (sym::Pedersen64, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashPED64Raw, LiteralType::I32),
            (sym::Pedersen64, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashPED64Raw, LiteralType::I64),
            (sym::Pedersen64, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashPED64Raw, LiteralType::I128),
            (sym::Pedersen64, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashPED64Raw, LiteralType::U8),
            (sym::Pedersen64, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashPED64Raw, LiteralType::U16),
            (sym::Pedersen64, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashPED64Raw, LiteralType::U32),
            (sym::Pedersen64, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashPED64Raw, LiteralType::U64),
            (sym::Pedersen64, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashPED64Raw, LiteralType::U128),
            (sym::Pedersen64, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashPED64Raw, LiteralType::Scalar),

            (sym::Pedersen128, sym::hash_to_address)     => Self::Hash(HashVariant::HashPED128, LiteralType::Address),
            (sym::Pedersen128, sym::hash_to_field)       => Self::Hash(HashVariant::HashPED128, LiteralType::Field),
            (sym::Pedersen128, sym::hash_to_group)       => Self::Hash(HashVariant::HashPED128, LiteralType::Group),
            (sym::Pedersen128, sym::hash_to_i8)          => Self::Hash(HashVariant::HashPED128, LiteralType::I8),
            (sym::Pedersen128, sym::hash_to_i16)         => Self::Hash(HashVariant::HashPED128, LiteralType::I16),
            (sym::Pedersen128, sym::hash_to_i32)         => Self::Hash(HashVariant::HashPED128, LiteralType::I32),
            (sym::Pedersen128, sym::hash_to_i64)         => Self::Hash(HashVariant::HashPED128, LiteralType::I64),
            (sym::Pedersen128, sym::hash_to_i128)        => Self::Hash(HashVariant::HashPED128, LiteralType::I128),
            (sym::Pedersen128, sym::hash_to_u8)          => Self::Hash(HashVariant::HashPED128, LiteralType::U8),
            (sym::Pedersen128, sym::hash_to_u16)         => Self::Hash(HashVariant::HashPED128, LiteralType::U16),
            (sym::Pedersen128, sym::hash_to_u32)         => Self::Hash(HashVariant::HashPED128, LiteralType::U32),
            (sym::Pedersen128, sym::hash_to_u64)         => Self::Hash(HashVariant::HashPED128, LiteralType::U64),
            (sym::Pedersen128, sym::hash_to_u128)        => Self::Hash(HashVariant::HashPED128, LiteralType::U128),
            (sym::Pedersen128, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashPED128, LiteralType::Scalar),
            (sym::Pedersen128, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashPED128Raw, LiteralType::Address),
            (sym::Pedersen128, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashPED128Raw, LiteralType::Field),
            (sym::Pedersen128, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashPED128Raw, LiteralType::Group),
            (sym::Pedersen128, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashPED128Raw, LiteralType::I8),
            (sym::Pedersen128, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashPED128Raw, LiteralType::I16),
            (sym::Pedersen128, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashPED128Raw, LiteralType::I32),
            (sym::Pedersen128, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashPED128Raw, LiteralType::I64),
            (sym::Pedersen128, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashPED128Raw, LiteralType::I128),
            (sym::Pedersen128, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashPED128Raw, LiteralType::U8),
            (sym::Pedersen128, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashPED128Raw, LiteralType::U16),
            (sym::Pedersen128, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashPED128Raw, LiteralType::U32),
            (sym::Pedersen128, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashPED128Raw, LiteralType::U64),
            (sym::Pedersen128, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashPED128Raw, LiteralType::U128),
            (sym::Pedersen128, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashPED128Raw, LiteralType::Scalar),

            (sym::Poseidon2, sym::hash_to_address)     => Self::Hash(HashVariant::HashPSD2, LiteralType::Address),
            (sym::Poseidon2, sym::hash_to_field)       => Self::Hash(HashVariant::HashPSD2, LiteralType::Field),
            (sym::Poseidon2, sym::hash_to_group)       => Self::Hash(HashVariant::HashPSD2, LiteralType::Group),
            (sym::Poseidon2, sym::hash_to_i8)          => Self::Hash(HashVariant::HashPSD2, LiteralType::I8),
            (sym::Poseidon2, sym::hash_to_i16)         => Self::Hash(HashVariant::HashPSD2, LiteralType::I16),
            (sym::Poseidon2, sym::hash_to_i32)         => Self::Hash(HashVariant::HashPSD2, LiteralType::I32),
            (sym::Poseidon2, sym::hash_to_i64)         => Self::Hash(HashVariant::HashPSD2, LiteralType::I64),
            (sym::Poseidon2, sym::hash_to_i128)        => Self::Hash(HashVariant::HashPSD2, LiteralType::I128),
            (sym::Poseidon2, sym::hash_to_u8)          => Self::Hash(HashVariant::HashPSD2, LiteralType::U8),
            (sym::Poseidon2, sym::hash_to_u16)         => Self::Hash(HashVariant::HashPSD2, LiteralType::U16),
            (sym::Poseidon2, sym::hash_to_u32)         => Self::Hash(HashVariant::HashPSD2, LiteralType::U32),
            (sym::Poseidon2, sym::hash_to_u64)         => Self::Hash(HashVariant::HashPSD2, LiteralType::U64),
            (sym::Poseidon2, sym::hash_to_u128)        => Self::Hash(HashVariant::HashPSD2, LiteralType::U128),
            (sym::Poseidon2, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashPSD2, LiteralType::Scalar),
            (sym::Poseidon2, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::Address),
            (sym::Poseidon2, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::Field),
            (sym::Poseidon2, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::Group),
            (sym::Poseidon2, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::I8),
            (sym::Poseidon2, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::I16),
            (sym::Poseidon2, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::I32),
            (sym::Poseidon2, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::I64),
            (sym::Poseidon2, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::I128),
            (sym::Poseidon2, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::U8),
            (sym::Poseidon2, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::U16),
            (sym::Poseidon2, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::U32),
            (sym::Poseidon2, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::U64),
            (sym::Poseidon2, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::U128),
            (sym::Poseidon2, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashPSD2Raw, LiteralType::Scalar),

            (sym::Poseidon4, sym::hash_to_address)     => Self::Hash(HashVariant::HashPSD4, LiteralType::Address),
            (sym::Poseidon4, sym::hash_to_field)       => Self::Hash(HashVariant::HashPSD4, LiteralType::Field),
            (sym::Poseidon4, sym::hash_to_group)       => Self::Hash(HashVariant::HashPSD4, LiteralType::Group),
            (sym::Poseidon4, sym::hash_to_i8)          => Self::Hash(HashVariant::HashPSD4, LiteralType::I8),
            (sym::Poseidon4, sym::hash_to_i16)         => Self::Hash(HashVariant::HashPSD4, LiteralType::I16),
            (sym::Poseidon4, sym::hash_to_i32)         => Self::Hash(HashVariant::HashPSD4, LiteralType::I32),
            (sym::Poseidon4, sym::hash_to_i64)         => Self::Hash(HashVariant::HashPSD4, LiteralType::I64),
            (sym::Poseidon4, sym::hash_to_i128)        => Self::Hash(HashVariant::HashPSD4, LiteralType::I128),
            (sym::Poseidon4, sym::hash_to_u8)          => Self::Hash(HashVariant::HashPSD4, LiteralType::U8),
            (sym::Poseidon4, sym::hash_to_u16)         => Self::Hash(HashVariant::HashPSD4, LiteralType::U16),
            (sym::Poseidon4, sym::hash_to_u32)         => Self::Hash(HashVariant::HashPSD4, LiteralType::U32),
            (sym::Poseidon4, sym::hash_to_u64)         => Self::Hash(HashVariant::HashPSD4, LiteralType::U64),
            (sym::Poseidon4, sym::hash_to_u128)        => Self::Hash(HashVariant::HashPSD4, LiteralType::U128),
            (sym::Poseidon4, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashPSD4, LiteralType::Scalar),
            (sym::Poseidon4, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::Address),
            (sym::Poseidon4, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::Field),
            (sym::Poseidon4, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::Group),
            (sym::Poseidon4, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::I8),
            (sym::Poseidon4, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::I16),
            (sym::Poseidon4, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::I32),
            (sym::Poseidon4, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::I64),
            (sym::Poseidon4, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::I128),
            (sym::Poseidon4, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::U8),
            (sym::Poseidon4, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::U16),
            (sym::Poseidon4, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::U32),
            (sym::Poseidon4, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::U64),
            (sym::Poseidon4, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::U128),
            (sym::Poseidon4, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashPSD4Raw, LiteralType::Scalar),

            (sym::Poseidon8, sym::hash_to_address)     => Self::Hash(HashVariant::HashPSD8, LiteralType::Address),
            (sym::Poseidon8, sym::hash_to_field)       => Self::Hash(HashVariant::HashPSD8, LiteralType::Field),
            (sym::Poseidon8, sym::hash_to_group)       => Self::Hash(HashVariant::HashPSD8, LiteralType::Group),
            (sym::Poseidon8, sym::hash_to_i8)          => Self::Hash(HashVariant::HashPSD8, LiteralType::I8),
            (sym::Poseidon8, sym::hash_to_i16)         => Self::Hash(HashVariant::HashPSD8, LiteralType::I16),
            (sym::Poseidon8, sym::hash_to_i32)         => Self::Hash(HashVariant::HashPSD8, LiteralType::I32),
            (sym::Poseidon8, sym::hash_to_i64)         => Self::Hash(HashVariant::HashPSD8, LiteralType::I64),
            (sym::Poseidon8, sym::hash_to_i128)        => Self::Hash(HashVariant::HashPSD8, LiteralType::I128),
            (sym::Poseidon8, sym::hash_to_u8)          => Self::Hash(HashVariant::HashPSD8, LiteralType::U8),
            (sym::Poseidon8, sym::hash_to_u16)         => Self::Hash(HashVariant::HashPSD8, LiteralType::U16),
            (sym::Poseidon8, sym::hash_to_u32)         => Self::Hash(HashVariant::HashPSD8, LiteralType::U32),
            (sym::Poseidon8, sym::hash_to_u64)         => Self::Hash(HashVariant::HashPSD8, LiteralType::U64),
            (sym::Poseidon8, sym::hash_to_u128)        => Self::Hash(HashVariant::HashPSD8, LiteralType::U128),
            (sym::Poseidon8, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashPSD8, LiteralType::Scalar),
            (sym::Poseidon8, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::Address),
            (sym::Poseidon8, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::Field),
            (sym::Poseidon8, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::Group),
            (sym::Poseidon8, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::I8),
            (sym::Poseidon8, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::I16),
            (sym::Poseidon8, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::I32),
            (sym::Poseidon8, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::I64),
            (sym::Poseidon8, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::I128),
            (sym::Poseidon8, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::U8),
            (sym::Poseidon8, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::U16),
            (sym::Poseidon8, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::U32),
            (sym::Poseidon8, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::U64),
            (sym::Poseidon8, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::U128),
            (sym::Poseidon8, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashPSD8Raw, LiteralType::Scalar),

            (sym::SHA3_256, sym::hash_to_address)     => Self::Hash(HashVariant::HashSha3_256, LiteralType::Address),
            (sym::SHA3_256, sym::hash_to_field)       => Self::Hash(HashVariant::HashSha3_256, LiteralType::Field),
            (sym::SHA3_256, sym::hash_to_group)       => Self::Hash(HashVariant::HashSha3_256, LiteralType::Group),
            (sym::SHA3_256, sym::hash_to_i8)          => Self::Hash(HashVariant::HashSha3_256, LiteralType::I8),
            (sym::SHA3_256, sym::hash_to_i16)         => Self::Hash(HashVariant::HashSha3_256, LiteralType::I16),
            (sym::SHA3_256, sym::hash_to_i32)         => Self::Hash(HashVariant::HashSha3_256, LiteralType::I32),
            (sym::SHA3_256, sym::hash_to_i64)         => Self::Hash(HashVariant::HashSha3_256, LiteralType::I64),
            (sym::SHA3_256, sym::hash_to_i128)        => Self::Hash(HashVariant::HashSha3_256, LiteralType::I128),
            (sym::SHA3_256, sym::hash_to_u8)          => Self::Hash(HashVariant::HashSha3_256, LiteralType::U8),
            (sym::SHA3_256, sym::hash_to_u16)         => Self::Hash(HashVariant::HashSha3_256, LiteralType::U16),
            (sym::SHA3_256, sym::hash_to_u32)         => Self::Hash(HashVariant::HashSha3_256, LiteralType::U32),
            (sym::SHA3_256, sym::hash_to_u64)         => Self::Hash(HashVariant::HashSha3_256, LiteralType::U64),
            (sym::SHA3_256, sym::hash_to_u128)        => Self::Hash(HashVariant::HashSha3_256, LiteralType::U128),
            (sym::SHA3_256, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashSha3_256, LiteralType::Scalar),
            (sym::SHA3_256, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::Address),
            (sym::SHA3_256, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::Field),
            (sym::SHA3_256, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::Group),
            (sym::SHA3_256, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::I8),
            (sym::SHA3_256, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::I16),
            (sym::SHA3_256, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::I32),
            (sym::SHA3_256, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::I64),
            (sym::SHA3_256, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::I128),
            (sym::SHA3_256, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::U8),
            (sym::SHA3_256, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::U16),
            (sym::SHA3_256, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::U32),
            (sym::SHA3_256, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::U64),
            (sym::SHA3_256, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::U128),
            (sym::SHA3_256, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashSha3_256Raw, LiteralType::Scalar),

            (sym::SHA3_384, sym::hash_to_address)     => Self::Hash(HashVariant::HashSha3_384, LiteralType::Address),
            (sym::SHA3_384, sym::hash_to_field)       => Self::Hash(HashVariant::HashSha3_384, LiteralType::Field),
            (sym::SHA3_384, sym::hash_to_group)       => Self::Hash(HashVariant::HashSha3_384, LiteralType::Group),
            (sym::SHA3_384, sym::hash_to_i8)          => Self::Hash(HashVariant::HashSha3_384, LiteralType::I8),
            (sym::SHA3_384, sym::hash_to_i16)         => Self::Hash(HashVariant::HashSha3_384, LiteralType::I16),
            (sym::SHA3_384, sym::hash_to_i32)         => Self::Hash(HashVariant::HashSha3_384, LiteralType::I32),
            (sym::SHA3_384, sym::hash_to_i64)         => Self::Hash(HashVariant::HashSha3_384, LiteralType::I64),
            (sym::SHA3_384, sym::hash_to_i128)        => Self::Hash(HashVariant::HashSha3_384, LiteralType::I128),
            (sym::SHA3_384, sym::hash_to_u8)          => Self::Hash(HashVariant::HashSha3_384, LiteralType::U8),
            (sym::SHA3_384, sym::hash_to_u16)         => Self::Hash(HashVariant::HashSha3_384, LiteralType::U16),
            (sym::SHA3_384, sym::hash_to_u32)         => Self::Hash(HashVariant::HashSha3_384, LiteralType::U32),
            (sym::SHA3_384, sym::hash_to_u64)         => Self::Hash(HashVariant::HashSha3_384, LiteralType::U64),
            (sym::SHA3_384, sym::hash_to_u128)        => Self::Hash(HashVariant::HashSha3_384, LiteralType::U128),
            (sym::SHA3_384, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashSha3_384, LiteralType::Scalar),
            (sym::SHA3_384, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::Address),
            (sym::SHA3_384, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::Field),
            (sym::SHA3_384, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::Group),
            (sym::SHA3_384, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::I8),
            (sym::SHA3_384, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::I16),
            (sym::SHA3_384, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::I32),
            (sym::SHA3_384, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::I64),
            (sym::SHA3_384, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::I128),
            (sym::SHA3_384, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::U8),
            (sym::SHA3_384, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::U16),
            (sym::SHA3_384, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::U32),
            (sym::SHA3_384, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::U64),
            (sym::SHA3_384, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::U128),
            (sym::SHA3_384, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashSha3_384Raw, LiteralType::Scalar),

            (sym::SHA3_512, sym::hash_to_address)     => Self::Hash(HashVariant::HashSha3_512, LiteralType::Address),
            (sym::SHA3_512, sym::hash_to_field)       => Self::Hash(HashVariant::HashSha3_512, LiteralType::Field),
            (sym::SHA3_512, sym::hash_to_group)       => Self::Hash(HashVariant::HashSha3_512, LiteralType::Group),
            (sym::SHA3_512, sym::hash_to_i8)          => Self::Hash(HashVariant::HashSha3_512, LiteralType::I8),
            (sym::SHA3_512, sym::hash_to_i16)         => Self::Hash(HashVariant::HashSha3_512, LiteralType::I16),
            (sym::SHA3_512, sym::hash_to_i32)         => Self::Hash(HashVariant::HashSha3_512, LiteralType::I32),
            (sym::SHA3_512, sym::hash_to_i64)         => Self::Hash(HashVariant::HashSha3_512, LiteralType::I64),
            (sym::SHA3_512, sym::hash_to_i128)        => Self::Hash(HashVariant::HashSha3_512, LiteralType::I128),
            (sym::SHA3_512, sym::hash_to_u8)          => Self::Hash(HashVariant::HashSha3_512, LiteralType::U8),
            (sym::SHA3_512, sym::hash_to_u16)         => Self::Hash(HashVariant::HashSha3_512, LiteralType::U16),
            (sym::SHA3_512, sym::hash_to_u32)         => Self::Hash(HashVariant::HashSha3_512, LiteralType::U32),
            (sym::SHA3_512, sym::hash_to_u64)         => Self::Hash(HashVariant::HashSha3_512, LiteralType::U64),
            (sym::SHA3_512, sym::hash_to_u128)        => Self::Hash(HashVariant::HashSha3_512, LiteralType::U128),
            (sym::SHA3_512, sym::hash_to_scalar)      => Self::Hash(HashVariant::HashSha3_512, LiteralType::Scalar),
            (sym::SHA3_512, sym::hash_to_address_raw) => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::Address),
            (sym::SHA3_512, sym::hash_to_field_raw)   => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::Field),
            (sym::SHA3_512, sym::hash_to_group_raw)   => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::Group),
            (sym::SHA3_512, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::I8),
            (sym::SHA3_512, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::I16),
            (sym::SHA3_512, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::I32),
            (sym::SHA3_512, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::I64),
            (sym::SHA3_512, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::I128),
            (sym::SHA3_512, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::U8),
            (sym::SHA3_512, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::U16),
            (sym::SHA3_512, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::U32),
            (sym::SHA3_512, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::U64),
            (sym::SHA3_512, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::U128),
            (sym::SHA3_512, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::HashSha3_512Raw, LiteralType::Scalar),

            (sym::ECDSA, sym::verify_keccak256)           => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak256),
            (sym::ECDSA, sym::verify_keccak256_raw)       => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak256Raw),
            (sym::ECDSA, sym::verify_keccak256_eth)       => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak256Eth),
            (sym::ECDSA, sym::verify_keccak384)           => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak384),
            (sym::ECDSA, sym::verify_keccak384_raw)       => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak384Raw),
            (sym::ECDSA, sym::verify_keccak384_eth)       => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak384Eth),
            (sym::ECDSA, sym::verify_keccak512)           => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak512),
            (sym::ECDSA, sym::verify_keccak512_raw)       => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak512Raw),
            (sym::ECDSA, sym::verify_keccak512_eth)       => Self::ECDSAVerify(ECDSAVerifyVariant::HashKeccak512Eth),
            (sym::ECDSA, sym::verify_sha3_256)            => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_256),
            (sym::ECDSA, sym::verify_sha3_256_raw)        => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_256Raw),
            (sym::ECDSA, sym::verify_sha3_256_eth)        => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_256Eth),
            (sym::ECDSA, sym::verify_sha3_384)            => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_384),
            (sym::ECDSA, sym::verify_sha3_384_raw)        => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_384Raw),
            (sym::ECDSA, sym::verify_sha3_384_eth)        => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_384Eth),
            (sym::ECDSA, sym::verify_sha3_512)            => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_512),
            (sym::ECDSA, sym::verify_sha3_512_raw)        => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_512Raw),
            (sym::ECDSA, sym::verify_sha3_512_eth)        => Self::ECDSAVerify(ECDSAVerifyVariant::HashSha3_512Eth),

            (sym::Mapping, sym::get) => Self::MappingGet,
            (sym::Mapping, sym::get_or_use) => Self::MappingGetOrUse,
            (sym::Mapping, sym::set) => Self::MappingSet,
            (sym::Mapping, sym::remove) => Self::MappingRemove,
            (sym::Mapping, sym::contains) => Self::MappingContains,

            (sym::group, sym::to_x_coordinate) => Self::GroupToXCoordinate,
            (sym::group, sym::to_y_coordinate) => Self::GroupToYCoordinate,

            (sym::ProgramCore, sym::checksum) => Self::ProgramChecksum,
            (sym::ProgramCore, sym::edition) => Self::ProgramEdition,
            (sym::ProgramCore, sym::program_owner) => Self::ProgramOwner,

            (sym::signature, sym::verify) => Self::SignatureVerify(false),
            (sym::signature, sym::verify_raw) => Self::SignatureVerify(true),
            (sym::Future, sym::Await) => Self::FutureAwait,

            (sym::CheatCode, sym::print_mapping) => Self::CheatCodePrintMapping,
            (sym::CheatCode, sym::set_block_height) => Self::CheatCodeSetBlockHeight,
            _ => return None,
        })
    }

    /// Returns the number of arguments required by the instruction.
    pub fn num_args(&self) -> usize {
        match self {
            Self::ChaChaRand(_) => 0,
            Self::Commit(_, _) => 2,
            Self::Hash(_, _) => 1,
            Self::ECDSAVerify(_) => 3,

            Self::MappingGet => 2,
            Self::MappingGetOrUse => 3,
            Self::MappingSet => 3,
            Self::MappingRemove => 2,
            Self::MappingContains => 2,

            Self::GroupToXCoordinate => 1,
            Self::GroupToYCoordinate => 1,

            Self::SignatureVerify(_) => 3,
            Self::FutureAwait => 1,

            Self::ProgramChecksum => 1,
            Self::ProgramEdition => 1,
            Self::ProgramOwner => 1,
            Self::CheatCodePrintMapping => 1,
            Self::CheatCodeSetBlockHeight => 1,
        }
    }

    /// Returns whether or not this function is finalize command.
    pub fn is_finalize_command(&self) -> bool {
        match self {
            CoreFunction::FutureAwait
            | CoreFunction::ChaChaRand(_)
            | CoreFunction::ECDSAVerify(_)
            | CoreFunction::MappingGet
            | CoreFunction::MappingGetOrUse
            | CoreFunction::MappingSet
            | CoreFunction::MappingRemove
            | CoreFunction::MappingContains
            | CoreFunction::ProgramChecksum
            | CoreFunction::ProgramEdition
            | CoreFunction::ProgramOwner => true,
            CoreFunction::Commit(_, _)
            | CoreFunction::Hash(_, _)
            | CoreFunction::GroupToXCoordinate
            | CoreFunction::GroupToYCoordinate
            | CoreFunction::SignatureVerify(_)
            | CoreFunction::CheatCodePrintMapping
            | CoreFunction::CheatCodeSetBlockHeight => false,
        }
    }
}
