// Copyright (C) 2019-2025 Provable Inc.
// This file is part of the Leo library.

// The Leo library is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// The Leo library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with the Leo library. If not, see <https://www.gnu.org/licenses/>.

use leo_span::{Symbol, sym};

use crate::{IntegerType, Type};

use std::fmt::{Display, Formatter};

/// A core instruction that maps directly to an AVM bytecode instruction.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CoreFunction {
    // ChaCha random value of type (Type).
    ChaChaRand(Type),
    // Commitment to a value using hash (HashVariant) returning value of type (Type).
    Commit(HashVariant, Type),
    // ECDSA verify with hash (HashVariant) using raw bytes (bool) and the ETH variant (bool).
    ECDSAVerify(HashVariant, bool, bool),
    // Hash function with variant (HashVariant), using raw bytes (bool), returning value of type (Type).
    Hash(HashVariant, bool, Type),

    MappingGet,
    MappingGetOrUse,
    MappingSet,
    MappingRemove,
    MappingContains,

    GroupToXCoordinate,
    GroupToYCoordinate,

    // Schnorr signature verification with raw (bool) bytes.
    SignatureVerify(bool),

    FutureAwait,

    ProgramChecksum,
    ProgramEdition,
    ProgramOwner,

    CheatCodePrintMapping,
    CheatCodeSetBlockHeight,
}

/// Hash variants.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum HashVariant {
    BHP256,
    BHP512,
    BHP768,
    BHP1024,
    Pedersen64,
    Pedersen128,
    Keccak256,
    Keccak384,
    Keccak512,
    Poseidon2,
    Poseidon4,
    Poseidon8,
    SHA3_256,
    SHA3_384,
    SHA3_512,
}

impl Display for HashVariant {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            HashVariant::BHP256 => write!(f, "bhp256"),
            HashVariant::BHP512 => write!(f, "bhp512"),
            HashVariant::BHP768 => write!(f, "bhp768"),
            HashVariant::BHP1024 => write!(f, "bhp1024"),
            HashVariant::Pedersen64 => write!(f, "ped64"),
            HashVariant::Pedersen128 => write!(f, "ped128"),
            HashVariant::Keccak256 => write!(f, "keccak256"),
            HashVariant::Keccak384 => write!(f, "keccak384"),
            HashVariant::Keccak512 => write!(f, "keccak512"),
            HashVariant::Poseidon2 => write!(f, "psd2"),
            HashVariant::Poseidon4 => write!(f, "psd4"),
            HashVariant::Poseidon8 => write!(f, "psd8"),
            HashVariant::SHA3_256 => write!(f, "sha3_256"),
            HashVariant::SHA3_384 => write!(f, "sha3_384"),
            HashVariant::SHA3_512 => write!(f, "sha3_512"),
        }
    }
}

impl CoreFunction {
    /// Returns a `CoreFunction` from the given module and method symbols.
    #[rustfmt::skip]
    pub fn from_symbols(module: Symbol, function: Symbol) -> Option<Self> {
        Some(match (module, function) {
            (sym::ChaCha, sym::rand_address) => Self::ChaChaRand(Type::Address),
            (sym::ChaCha, sym::rand_bool)    => Self::ChaChaRand(Type::Boolean),
            (sym::ChaCha, sym::rand_field)   => Self::ChaChaRand(Type::Field),
            (sym::ChaCha, sym::rand_group)   => Self::ChaChaRand(Type::Group),
            (sym::ChaCha, sym::rand_i8)      => Self::ChaChaRand(Type::Integer(IntegerType::I8)),
            (sym::ChaCha, sym::rand_i16)     => Self::ChaChaRand(Type::Integer(IntegerType::I16)),
            (sym::ChaCha, sym::rand_i32)     => Self::ChaChaRand(Type::Integer(IntegerType::I32)),
            (sym::ChaCha, sym::rand_i64)     => Self::ChaChaRand(Type::Integer(IntegerType::I64)),
            (sym::ChaCha, sym::rand_i128)    => Self::ChaChaRand(Type::Integer(IntegerType::I128)),
            (sym::ChaCha, sym::rand_u8)      => Self::ChaChaRand(Type::Integer(IntegerType::U8)),
            (sym::ChaCha, sym::rand_u16)     => Self::ChaChaRand(Type::Integer(IntegerType::U16)),
            (sym::ChaCha, sym::rand_u32)     => Self::ChaChaRand(Type::Integer(IntegerType::U32)),
            (sym::ChaCha, sym::rand_u64)     => Self::ChaChaRand(Type::Integer(IntegerType::U64)),
            (sym::ChaCha, sym::rand_u128)    => Self::ChaChaRand(Type::Integer(IntegerType::U128)),
            (sym::ChaCha, sym::rand_scalar)  => Self::ChaChaRand(Type::Scalar),

            (sym::BHP256, sym::commit_to_address)   => Self::Commit(HashVariant::BHP256, Type::Address),
            (sym::BHP256, sym::commit_to_field)     => Self::Commit(HashVariant::BHP256, Type::Field),
            (sym::BHP256, sym::commit_to_group)     => Self::Commit(HashVariant::BHP256, Type::Group),
            (sym::BHP512, sym::commit_to_address)   => Self::Commit(HashVariant::BHP256, Type::Address),
            (sym::BHP512, sym::commit_to_field)     => Self::Commit(HashVariant::BHP256, Type::Field),
            (sym::BHP512, sym::commit_to_group)     => Self::Commit(HashVariant::BHP256, Type::Group),
            (sym::BHP768, sym::commit_to_address)   => Self::Commit(HashVariant::BHP256, Type::Address),
            (sym::BHP768, sym::commit_to_field)     => Self::Commit(HashVariant::BHP256, Type::Field),
            (sym::BHP768, sym::commit_to_group)     => Self::Commit(HashVariant::BHP256, Type::Group),
            (sym::BHP1024, sym::commit_to_address)   => Self::Commit(HashVariant::BHP256, Type::Address),
            (sym::BHP1024, sym::commit_to_field)     => Self::Commit(HashVariant::BHP256, Type::Field),
            (sym::BHP1024, sym::commit_to_group)     => Self::Commit(HashVariant::BHP256, Type::Group),
            (sym::Pedersen64, sym::commit_to_address)   => Self::Commit(HashVariant::BHP256, Type::Address),
            (sym::Pedersen64, sym::commit_to_field)     => Self::Commit(HashVariant::BHP256, Type::Field),
            (sym::Pedersen64, sym::commit_to_group)     => Self::Commit(HashVariant::BHP256, Type::Group),
            (sym::Pedersen128, sym::commit_to_address)   => Self::Commit(HashVariant::BHP256, Type::Address),
            (sym::Pedersen128, sym::commit_to_field)     => Self::Commit(HashVariant::BHP256, Type::Field),
            (sym::Pedersen128, sym::commit_to_group)     => Self::Commit(HashVariant::BHP256, Type::Group),

            (sym::BHP256, sym::hash_to_address)     => Self::Hash(HashVariant::BHP256, false, Type::Address),
            (sym::BHP256, sym::hash_to_field)       => Self::Hash(HashVariant::BHP256, false, Type::Field),
            (sym::BHP256, sym::hash_to_group)       => Self::Hash(HashVariant::BHP256, false, Type::Group),
            (sym::BHP256, sym::hash_to_i8)          => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::I8)),
            (sym::BHP256, sym::hash_to_i16)         => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::I16)),
            (sym::BHP256, sym::hash_to_i32)         => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::I32)),
            (sym::BHP256, sym::hash_to_i64)         => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::I64)),
            (sym::BHP256, sym::hash_to_i128)        => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::I128)),
            (sym::BHP256, sym::hash_to_u8)          => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::U8)),
            (sym::BHP256, sym::hash_to_u16)         => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::U16)),
            (sym::BHP256, sym::hash_to_u32)         => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::U32)),
            (sym::BHP256, sym::hash_to_u64)         => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::U64)),
            (sym::BHP256, sym::hash_to_u128)        => Self::Hash(HashVariant::BHP256, false, Type::Integer(IntegerType::U128)),
            (sym::BHP256, sym::hash_to_scalar)      => Self::Hash(HashVariant::BHP256, false, Type::Scalar),
            (sym::BHP256, sym::hash_to_address_raw) => Self::Hash(HashVariant::BHP256, true, Type::Address),
            (sym::BHP256, sym::hash_to_field_raw)   => Self::Hash(HashVariant::BHP256, true, Type::Field),
            (sym::BHP256, sym::hash_to_group_raw)   => Self::Hash(HashVariant::BHP256, true, Type::Group),
            (sym::BHP256, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::I8)),
            (sym::BHP256, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::I16)),
            (sym::BHP256, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::I32)),
            (sym::BHP256, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::I64)),
            (sym::BHP256, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::I128)),
            (sym::BHP256, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::U8)),
            (sym::BHP256, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::U16)),
            (sym::BHP256, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::U32)),
            (sym::BHP256, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::U64)),
            (sym::BHP256, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::BHP256, true, Type::Integer(IntegerType::U128)),
            (sym::BHP256, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::BHP256, true, Type::Scalar),

            (sym::BHP512, sym::hash_to_address)     => Self::Hash(HashVariant::BHP512, false, Type::Address),
            (sym::BHP512, sym::hash_to_field)       => Self::Hash(HashVariant::BHP512, false, Type::Field),
            (sym::BHP512, sym::hash_to_group)       => Self::Hash(HashVariant::BHP512, false, Type::Group),
            (sym::BHP512, sym::hash_to_i8)          => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::I8)),
            (sym::BHP512, sym::hash_to_i16)         => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::I16)),
            (sym::BHP512, sym::hash_to_i32)         => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::I32)),
            (sym::BHP512, sym::hash_to_i64)         => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::I64)),
            (sym::BHP512, sym::hash_to_i128)        => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::I128)),
            (sym::BHP512, sym::hash_to_u8)          => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::U8)),
            (sym::BHP512, sym::hash_to_u16)         => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::U16)),
            (sym::BHP512, sym::hash_to_u32)         => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::U32)),
            (sym::BHP512, sym::hash_to_u64)         => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::U64)),
            (sym::BHP512, sym::hash_to_u128)        => Self::Hash(HashVariant::BHP512, false, Type::Integer(IntegerType::U128)),
            (sym::BHP512, sym::hash_to_scalar)      => Self::Hash(HashVariant::BHP512, false, Type::Scalar),
            (sym::BHP512, sym::hash_to_address_raw) => Self::Hash(HashVariant::BHP512, true, Type::Address),
            (sym::BHP512, sym::hash_to_field_raw)   => Self::Hash(HashVariant::BHP512, true, Type::Field),
            (sym::BHP512, sym::hash_to_group_raw)   => Self::Hash(HashVariant::BHP512, true, Type::Group),
            (sym::BHP512, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::I8)),
            (sym::BHP512, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::I16)),
            (sym::BHP512, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::I32)),
            (sym::BHP512, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::I64)),
            (sym::BHP512, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::I128)),
            (sym::BHP512, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::U8)),
            (sym::BHP512, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::U16)),
            (sym::BHP512, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::U32)),
            (sym::BHP512, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::U64)),
            (sym::BHP512, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::BHP512, true, Type::Integer(IntegerType::U128)),
            (sym::BHP512, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::BHP512, true, Type::Scalar),

            (sym::BHP768, sym::hash_to_address)     => Self::Hash(HashVariant::BHP768, false, Type::Address),
            (sym::BHP768, sym::hash_to_field)       => Self::Hash(HashVariant::BHP768, false, Type::Field),
            (sym::BHP768, sym::hash_to_group)       => Self::Hash(HashVariant::BHP768, false, Type::Group),
            (sym::BHP768, sym::hash_to_i8)          => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::I8)),
            (sym::BHP768, sym::hash_to_i16)         => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::I16)),
            (sym::BHP768, sym::hash_to_i32)         => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::I32)),
            (sym::BHP768, sym::hash_to_i64)         => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::I64)),
            (sym::BHP768, sym::hash_to_i128)        => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::I128)),
            (sym::BHP768, sym::hash_to_u8)          => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::U8)),
            (sym::BHP768, sym::hash_to_u16)         => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::U16)),
            (sym::BHP768, sym::hash_to_u32)         => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::U32)),
            (sym::BHP768, sym::hash_to_u64)         => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::U64)),
            (sym::BHP768, sym::hash_to_u128)        => Self::Hash(HashVariant::BHP768, false, Type::Integer(IntegerType::U128)),
            (sym::BHP768, sym::hash_to_scalar)      => Self::Hash(HashVariant::BHP768, false, Type::Scalar),
            (sym::BHP768, sym::hash_to_address_raw) => Self::Hash(HashVariant::BHP768, true, Type::Address),
            (sym::BHP768, sym::hash_to_field_raw)   => Self::Hash(HashVariant::BHP768, true, Type::Field),
            (sym::BHP768, sym::hash_to_group_raw)   => Self::Hash(HashVariant::BHP768, true, Type::Group),
            (sym::BHP768, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::I8)),
            (sym::BHP768, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::I16)),
            (sym::BHP768, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::I32)),
            (sym::BHP768, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::I64)),
            (sym::BHP768, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::I128)),
            (sym::BHP768, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::U8)),
            (sym::BHP768, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::U16)),
            (sym::BHP768, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::U32)),
            (sym::BHP768, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::U64)),
            (sym::BHP768, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::BHP768, true, Type::Integer(IntegerType::U128)),
            (sym::BHP768, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::BHP768, true, Type::Scalar),

            (sym::BHP1024, sym::hash_to_address)     => Self::Hash(HashVariant::BHP1024, false, Type::Address),
            (sym::BHP1024, sym::hash_to_field)       => Self::Hash(HashVariant::BHP1024, false, Type::Field),
            (sym::BHP1024, sym::hash_to_group)       => Self::Hash(HashVariant::BHP1024, false, Type::Group),
            (sym::BHP1024, sym::hash_to_i8)          => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::I8)),
            (sym::BHP1024, sym::hash_to_i16)         => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::I16)),
            (sym::BHP1024, sym::hash_to_i32)         => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::I32)),
            (sym::BHP1024, sym::hash_to_i64)         => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::I64)),
            (sym::BHP1024, sym::hash_to_i128)        => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::I128)),
            (sym::BHP1024, sym::hash_to_u8)          => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::U8)),
            (sym::BHP1024, sym::hash_to_u16)         => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::U16)),
            (sym::BHP1024, sym::hash_to_u32)         => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::U32)),
            (sym::BHP1024, sym::hash_to_u64)         => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::U64)),
            (sym::BHP1024, sym::hash_to_u128)        => Self::Hash(HashVariant::BHP1024, false, Type::Integer(IntegerType::U128)),
            (sym::BHP1024, sym::hash_to_scalar)      => Self::Hash(HashVariant::BHP1024, false, Type::Scalar),
            (sym::BHP1024, sym::hash_to_address_raw) => Self::Hash(HashVariant::BHP1024, true, Type::Address),
            (sym::BHP1024, sym::hash_to_field_raw)   => Self::Hash(HashVariant::BHP1024, true, Type::Field),
            (sym::BHP1024, sym::hash_to_group_raw)   => Self::Hash(HashVariant::BHP1024, true, Type::Group),
            (sym::BHP1024, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::I8)),
            (sym::BHP1024, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::I16)),
            (sym::BHP1024, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::I32)),
            (sym::BHP1024, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::I64)),
            (sym::BHP1024, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::I128)),
            (sym::BHP1024, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::U8)),
            (sym::BHP1024, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::U16)),
            (sym::BHP1024, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::U32)),
            (sym::BHP1024, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::U64)),
            (sym::BHP1024, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::BHP1024, true, Type::Integer(IntegerType::U128)),
            (sym::BHP1024, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::BHP1024, true, Type::Scalar),

            (sym::Keccak256, sym::hash_to_address)     => Self::Hash(HashVariant::Keccak256, false, Type::Address),
            (sym::Keccak256, sym::hash_to_field)       => Self::Hash(HashVariant::Keccak256, false, Type::Field),
            (sym::Keccak256, sym::hash_to_group)       => Self::Hash(HashVariant::Keccak256, false, Type::Group),
            (sym::Keccak256, sym::hash_to_i8)          => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::I8)),
            (sym::Keccak256, sym::hash_to_i16)         => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::I16)),
            (sym::Keccak256, sym::hash_to_i32)         => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::I32)),
            (sym::Keccak256, sym::hash_to_i64)         => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::I64)),
            (sym::Keccak256, sym::hash_to_i128)        => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::I128)),
            (sym::Keccak256, sym::hash_to_u8)          => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::U8)),
            (sym::Keccak256, sym::hash_to_u16)         => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::U16)),
            (sym::Keccak256, sym::hash_to_u32)         => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::U32)),
            (sym::Keccak256, sym::hash_to_u64)         => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::U64)),
            (sym::Keccak256, sym::hash_to_u128)        => Self::Hash(HashVariant::Keccak256, false, Type::Integer(IntegerType::U128)),
            (sym::Keccak256, sym::hash_to_scalar)      => Self::Hash(HashVariant::Keccak256, false, Type::Scalar),
            (sym::Keccak256, sym::hash_to_address_raw) => Self::Hash(HashVariant::Keccak256, true, Type::Address),
            (sym::Keccak256, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Keccak256, true, Type::Field),
            (sym::Keccak256, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Keccak256, true, Type::Group),
            (sym::Keccak256, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::I8)),
            (sym::Keccak256, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::I16)),
            (sym::Keccak256, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::I32)),
            (sym::Keccak256, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::I64)),
            (sym::Keccak256, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::I128)),
            (sym::Keccak256, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::U8)),
            (sym::Keccak256, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::U16)),
            (sym::Keccak256, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::U32)),
            (sym::Keccak256, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::U64)),
            (sym::Keccak256, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Keccak256, true, Type::Integer(IntegerType::U128)),
            (sym::Keccak256, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Keccak256, true, Type::Scalar),

            (sym::Keccak384, sym::hash_to_address)     => Self::Hash(HashVariant::Keccak384, false, Type::Address),
            (sym::Keccak384, sym::hash_to_field)       => Self::Hash(HashVariant::Keccak384, false, Type::Field),
            (sym::Keccak384, sym::hash_to_group)       => Self::Hash(HashVariant::Keccak384, false, Type::Group),
            (sym::Keccak384, sym::hash_to_i8)          => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::I8)),
            (sym::Keccak384, sym::hash_to_i16)         => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::I16)),
            (sym::Keccak384, sym::hash_to_i32)         => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::I32)),
            (sym::Keccak384, sym::hash_to_i64)         => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::I64)),
            (sym::Keccak384, sym::hash_to_i128)        => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::I128)),
            (sym::Keccak384, sym::hash_to_u8)          => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::U8)),
            (sym::Keccak384, sym::hash_to_u16)         => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::U16)),
            (sym::Keccak384, sym::hash_to_u32)         => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::U32)),
            (sym::Keccak384, sym::hash_to_u64)         => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::U64)),
            (sym::Keccak384, sym::hash_to_u128)        => Self::Hash(HashVariant::Keccak384, false, Type::Integer(IntegerType::U128)),
            (sym::Keccak384, sym::hash_to_scalar)      => Self::Hash(HashVariant::Keccak384, false, Type::Scalar),
            (sym::Keccak384, sym::hash_to_address_raw) => Self::Hash(HashVariant::Keccak384, true, Type::Address),
            (sym::Keccak384, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Keccak384, true, Type::Field),
            (sym::Keccak384, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Keccak384, true, Type::Group),
            (sym::Keccak384, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::I8)),
            (sym::Keccak384, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::I16)),
            (sym::Keccak384, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::I32)),
            (sym::Keccak384, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::I64)),
            (sym::Keccak384, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::I128)),
            (sym::Keccak384, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::U8)),
            (sym::Keccak384, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::U16)),
            (sym::Keccak384, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::U32)),
            (sym::Keccak384, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::U64)),
            (sym::Keccak384, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Keccak384, true, Type::Integer(IntegerType::U128)),
            (sym::Keccak384, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Keccak384, true, Type::Scalar),

            (sym::Keccak512, sym::hash_to_address)     => Self::Hash(HashVariant::Keccak512, false, Type::Address),
            (sym::Keccak512, sym::hash_to_field)       => Self::Hash(HashVariant::Keccak512, false, Type::Field),
            (sym::Keccak512, sym::hash_to_group)       => Self::Hash(HashVariant::Keccak512, false, Type::Group),
            (sym::Keccak512, sym::hash_to_i8)          => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::I8)),
            (sym::Keccak512, sym::hash_to_i16)         => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::I16)),
            (sym::Keccak512, sym::hash_to_i32)         => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::I32)),
            (sym::Keccak512, sym::hash_to_i64)         => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::I64)),
            (sym::Keccak512, sym::hash_to_i128)        => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::I128)),
            (sym::Keccak512, sym::hash_to_u8)          => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::U8)),
            (sym::Keccak512, sym::hash_to_u16)         => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::U16)),
            (sym::Keccak512, sym::hash_to_u32)         => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::U32)),
            (sym::Keccak512, sym::hash_to_u64)         => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::U64)),
            (sym::Keccak512, sym::hash_to_u128)        => Self::Hash(HashVariant::Keccak512, false, Type::Integer(IntegerType::U128)),
            (sym::Keccak512, sym::hash_to_scalar)      => Self::Hash(HashVariant::Keccak512, false, Type::Scalar),
            (sym::Keccak512, sym::hash_to_address_raw) => Self::Hash(HashVariant::Keccak512, true, Type::Address),
            (sym::Keccak512, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Keccak512, true, Type::Field),
            (sym::Keccak512, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Keccak512, true, Type::Group),
            (sym::Keccak512, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::I8)),
            (sym::Keccak512, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::I16)),
            (sym::Keccak512, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::I32)),
            (sym::Keccak512, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::I64)),
            (sym::Keccak512, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::I128)),
            (sym::Keccak512, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::U8)),
            (sym::Keccak512, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::U16)),
            (sym::Keccak512, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::U32)),
            (sym::Keccak512, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::U64)),
            (sym::Keccak512, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Keccak512, true, Type::Integer(IntegerType::U128)),
            (sym::Keccak512, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Keccak512, true, Type::Scalar),

            (sym::Pedersen64, sym::hash_to_address)     => Self::Hash(HashVariant::Pedersen64, false, Type::Address),
            (sym::Pedersen64, sym::hash_to_field)       => Self::Hash(HashVariant::Pedersen64, false, Type::Field),
            (sym::Pedersen64, sym::hash_to_group)       => Self::Hash(HashVariant::Pedersen64, false, Type::Group),
            (sym::Pedersen64, sym::hash_to_i8)          => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::I8)),
            (sym::Pedersen64, sym::hash_to_i16)         => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::I16)),
            (sym::Pedersen64, sym::hash_to_i32)         => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::I32)),
            (sym::Pedersen64, sym::hash_to_i64)         => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::I64)),
            (sym::Pedersen64, sym::hash_to_i128)        => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::I128)),
            (sym::Pedersen64, sym::hash_to_u8)          => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::U8)),
            (sym::Pedersen64, sym::hash_to_u16)         => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::U16)),
            (sym::Pedersen64, sym::hash_to_u32)         => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::U32)),
            (sym::Pedersen64, sym::hash_to_u64)         => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::U64)),
            (sym::Pedersen64, sym::hash_to_u128)        => Self::Hash(HashVariant::Pedersen64, false, Type::Integer(IntegerType::U128)),
            (sym::Pedersen64, sym::hash_to_scalar)      => Self::Hash(HashVariant::Pedersen64, false, Type::Scalar),
            (sym::Pedersen64, sym::hash_to_address_raw) => Self::Hash(HashVariant::Pedersen64, true, Type::Address),
            (sym::Pedersen64, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Pedersen64, true, Type::Field),
            (sym::Pedersen64, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Pedersen64, true, Type::Group),
            (sym::Pedersen64, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::I8)),
            (sym::Pedersen64, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::I16)),
            (sym::Pedersen64, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::I32)),
            (sym::Pedersen64, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::I64)),
            (sym::Pedersen64, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::I128)),
            (sym::Pedersen64, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::U8)),
            (sym::Pedersen64, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::U16)),
            (sym::Pedersen64, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::U32)),
            (sym::Pedersen64, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::U64)),
            (sym::Pedersen64, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Pedersen64, true, Type::Integer(IntegerType::U128)),
            (sym::Pedersen64, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Pedersen64, true, Type::Scalar),

            (sym::Pedersen128, sym::hash_to_address)     => Self::Hash(HashVariant::Pedersen128, false, Type::Address),
            (sym::Pedersen128, sym::hash_to_field)       => Self::Hash(HashVariant::Pedersen128, false, Type::Field),
            (sym::Pedersen128, sym::hash_to_group)       => Self::Hash(HashVariant::Pedersen128, false, Type::Group),
            (sym::Pedersen128, sym::hash_to_i8)          => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::I8)),
            (sym::Pedersen128, sym::hash_to_i16)         => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::I16)),
            (sym::Pedersen128, sym::hash_to_i32)         => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::I32)),
            (sym::Pedersen128, sym::hash_to_i64)         => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::I64)),
            (sym::Pedersen128, sym::hash_to_i128)        => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::I128)),
            (sym::Pedersen128, sym::hash_to_u8)          => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::U8)),
            (sym::Pedersen128, sym::hash_to_u16)         => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::U16)),
            (sym::Pedersen128, sym::hash_to_u32)         => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::U32)),
            (sym::Pedersen128, sym::hash_to_u64)         => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::U64)),
            (sym::Pedersen128, sym::hash_to_u128)        => Self::Hash(HashVariant::Pedersen128, false, Type::Integer(IntegerType::U128)),
            (sym::Pedersen128, sym::hash_to_scalar)      => Self::Hash(HashVariant::Pedersen128, false, Type::Scalar),
            (sym::Pedersen128, sym::hash_to_address_raw) => Self::Hash(HashVariant::Pedersen128, true, Type::Address),
            (sym::Pedersen128, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Pedersen128, true, Type::Field),
            (sym::Pedersen128, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Pedersen128, true, Type::Group),
            (sym::Pedersen128, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::I8)),
            (sym::Pedersen128, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::I16)),
            (sym::Pedersen128, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::I32)),
            (sym::Pedersen128, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::I64)),
            (sym::Pedersen128, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::I128)),
            (sym::Pedersen128, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::U8)),
            (sym::Pedersen128, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::U16)),
            (sym::Pedersen128, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::U32)),
            (sym::Pedersen128, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::U64)),
            (sym::Pedersen128, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Pedersen128, true, Type::Integer(IntegerType::U128)),
            (sym::Pedersen128, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Pedersen128, true, Type::Scalar),

            (sym::Poseidon2, sym::hash_to_address)     => Self::Hash(HashVariant::Poseidon2, false, Type::Address),
            (sym::Poseidon2, sym::hash_to_field)       => Self::Hash(HashVariant::Poseidon2, false, Type::Field),
            (sym::Poseidon2, sym::hash_to_group)       => Self::Hash(HashVariant::Poseidon2, false, Type::Group),
            (sym::Poseidon2, sym::hash_to_i8)          => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::I8)),
            (sym::Poseidon2, sym::hash_to_i16)         => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::I16)),
            (sym::Poseidon2, sym::hash_to_i32)         => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::I32)),
            (sym::Poseidon2, sym::hash_to_i64)         => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::I64)),
            (sym::Poseidon2, sym::hash_to_i128)        => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::I128)),
            (sym::Poseidon2, sym::hash_to_u8)          => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::U8)),
            (sym::Poseidon2, sym::hash_to_u16)         => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::U16)),
            (sym::Poseidon2, sym::hash_to_u32)         => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::U32)),
            (sym::Poseidon2, sym::hash_to_u64)         => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::U64)),
            (sym::Poseidon2, sym::hash_to_u128)        => Self::Hash(HashVariant::Poseidon2, false, Type::Integer(IntegerType::U128)),
            (sym::Poseidon2, sym::hash_to_scalar)      => Self::Hash(HashVariant::Poseidon2, false, Type::Scalar),
            (sym::Poseidon2, sym::hash_to_address_raw) => Self::Hash(HashVariant::Poseidon2, true, Type::Address),
            (sym::Poseidon2, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Poseidon2, true, Type::Field),
            (sym::Poseidon2, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Poseidon2, true, Type::Group),
            (sym::Poseidon2, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::I8)),
            (sym::Poseidon2, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::I16)),
            (sym::Poseidon2, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::I32)),
            (sym::Poseidon2, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::I64)),
            (sym::Poseidon2, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::I128)),
            (sym::Poseidon2, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::U8)),
            (sym::Poseidon2, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::U16)),
            (sym::Poseidon2, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::U32)),
            (sym::Poseidon2, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::U64)),
            (sym::Poseidon2, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Poseidon2, true, Type::Integer(IntegerType::U128)),
            (sym::Poseidon2, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Poseidon2, true, Type::Scalar),

            (sym::Poseidon4, sym::hash_to_address)     => Self::Hash(HashVariant::Poseidon4, false, Type::Address),
            (sym::Poseidon4, sym::hash_to_field)       => Self::Hash(HashVariant::Poseidon4, false, Type::Field),
            (sym::Poseidon4, sym::hash_to_group)       => Self::Hash(HashVariant::Poseidon4, false, Type::Group),
            (sym::Poseidon4, sym::hash_to_i8)          => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::I8)),
            (sym::Poseidon4, sym::hash_to_i16)         => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::I16)),
            (sym::Poseidon4, sym::hash_to_i32)         => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::I32)),
            (sym::Poseidon4, sym::hash_to_i64)         => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::I64)),
            (sym::Poseidon4, sym::hash_to_i128)        => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::I128)),
            (sym::Poseidon4, sym::hash_to_u8)          => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::U8)),
            (sym::Poseidon4, sym::hash_to_u16)         => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::U16)),
            (sym::Poseidon4, sym::hash_to_u32)         => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::U32)),
            (sym::Poseidon4, sym::hash_to_u64)         => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::U64)),
            (sym::Poseidon4, sym::hash_to_u128)        => Self::Hash(HashVariant::Poseidon4, false, Type::Integer(IntegerType::U128)),
            (sym::Poseidon4, sym::hash_to_scalar)      => Self::Hash(HashVariant::Poseidon4, false, Type::Scalar),
            (sym::Poseidon4, sym::hash_to_address_raw) => Self::Hash(HashVariant::Poseidon4, true, Type::Address),
            (sym::Poseidon4, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Poseidon4, true, Type::Field),
            (sym::Poseidon4, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Poseidon4, true, Type::Group),
            (sym::Poseidon4, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::I8)),
            (sym::Poseidon4, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::I16)),
            (sym::Poseidon4, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::I32)),
            (sym::Poseidon4, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::I64)),
            (sym::Poseidon4, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::I128)),
            (sym::Poseidon4, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::U8)),
            (sym::Poseidon4, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::U16)),
            (sym::Poseidon4, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::U32)),
            (sym::Poseidon4, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::U64)),
            (sym::Poseidon4, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Poseidon4, true, Type::Integer(IntegerType::U128)),
            (sym::Poseidon4, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Poseidon4, true, Type::Scalar),

            (sym::Poseidon8, sym::hash_to_address)     => Self::Hash(HashVariant::Poseidon8, false, Type::Address),
            (sym::Poseidon8, sym::hash_to_field)       => Self::Hash(HashVariant::Poseidon8, false, Type::Field),
            (sym::Poseidon8, sym::hash_to_group)       => Self::Hash(HashVariant::Poseidon8, false, Type::Group),
            (sym::Poseidon8, sym::hash_to_i8)          => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::I8)),
            (sym::Poseidon8, sym::hash_to_i16)         => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::I16)),
            (sym::Poseidon8, sym::hash_to_i32)         => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::I32)),
            (sym::Poseidon8, sym::hash_to_i64)         => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::I64)),
            (sym::Poseidon8, sym::hash_to_i128)        => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::I128)),
            (sym::Poseidon8, sym::hash_to_u8)          => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::U8)),
            (sym::Poseidon8, sym::hash_to_u16)         => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::U16)),
            (sym::Poseidon8, sym::hash_to_u32)         => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::U32)),
            (sym::Poseidon8, sym::hash_to_u64)         => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::U64)),
            (sym::Poseidon8, sym::hash_to_u128)        => Self::Hash(HashVariant::Poseidon8, false, Type::Integer(IntegerType::U128)),
            (sym::Poseidon8, sym::hash_to_scalar)      => Self::Hash(HashVariant::Poseidon8, false, Type::Scalar),
            (sym::Poseidon8, sym::hash_to_address_raw) => Self::Hash(HashVariant::Poseidon8, true, Type::Address),
            (sym::Poseidon8, sym::hash_to_field_raw)   => Self::Hash(HashVariant::Poseidon8, true, Type::Field),
            (sym::Poseidon8, sym::hash_to_group_raw)   => Self::Hash(HashVariant::Poseidon8, true, Type::Group),
            (sym::Poseidon8, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::I8)),
            (sym::Poseidon8, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::I16)),
            (sym::Poseidon8, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::I32)),
            (sym::Poseidon8, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::I64)),
            (sym::Poseidon8, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::I128)),
            (sym::Poseidon8, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::U8)),
            (sym::Poseidon8, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::U16)),
            (sym::Poseidon8, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::U32)),
            (sym::Poseidon8, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::U64)),
            (sym::Poseidon8, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::Poseidon8, true, Type::Integer(IntegerType::U128)),
            (sym::Poseidon8, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::Poseidon8, true, Type::Scalar),

            (sym::SHA3_256, sym::hash_to_address)     => Self::Hash(HashVariant::SHA3_256, false, Type::Address),
            (sym::SHA3_256, sym::hash_to_field)       => Self::Hash(HashVariant::SHA3_256, false, Type::Field),
            (sym::SHA3_256, sym::hash_to_group)       => Self::Hash(HashVariant::SHA3_256, false, Type::Group),
            (sym::SHA3_256, sym::hash_to_i8)          => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::I8)),
            (sym::SHA3_256, sym::hash_to_i16)         => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::I16)),
            (sym::SHA3_256, sym::hash_to_i32)         => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::I32)),
            (sym::SHA3_256, sym::hash_to_i64)         => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::I64)),
            (sym::SHA3_256, sym::hash_to_i128)        => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::I128)),
            (sym::SHA3_256, sym::hash_to_u8)          => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::U8)),
            (sym::SHA3_256, sym::hash_to_u16)         => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::U16)),
            (sym::SHA3_256, sym::hash_to_u32)         => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::U32)),
            (sym::SHA3_256, sym::hash_to_u64)         => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::U64)),
            (sym::SHA3_256, sym::hash_to_u128)        => Self::Hash(HashVariant::SHA3_256, false, Type::Integer(IntegerType::U128)),
            (sym::SHA3_256, sym::hash_to_scalar)      => Self::Hash(HashVariant::SHA3_256, false, Type::Scalar),
            (sym::SHA3_256, sym::hash_to_address_raw) => Self::Hash(HashVariant::SHA3_256, true, Type::Address),
            (sym::SHA3_256, sym::hash_to_field_raw)   => Self::Hash(HashVariant::SHA3_256, true, Type::Field),
            (sym::SHA3_256, sym::hash_to_group_raw)   => Self::Hash(HashVariant::SHA3_256, true, Type::Group),
            (sym::SHA3_256, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::I8)),
            (sym::SHA3_256, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::I16)),
            (sym::SHA3_256, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::I32)),
            (sym::SHA3_256, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::I64)),
            (sym::SHA3_256, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::I128)),
            (sym::SHA3_256, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::U8)),
            (sym::SHA3_256, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::U16)),
            (sym::SHA3_256, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::U32)),
            (sym::SHA3_256, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::U64)),
            (sym::SHA3_256, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::SHA3_256, true, Type::Integer(IntegerType::U128)),
            (sym::SHA3_256, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::SHA3_256, true, Type::Scalar),

            (sym::SHA3_384, sym::hash_to_address)     => Self::Hash(HashVariant::SHA3_384, false, Type::Address),
            (sym::SHA3_384, sym::hash_to_field)       => Self::Hash(HashVariant::SHA3_384, false, Type::Field),
            (sym::SHA3_384, sym::hash_to_group)       => Self::Hash(HashVariant::SHA3_384, false, Type::Group),
            (sym::SHA3_384, sym::hash_to_i8)          => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::I8)),
            (sym::SHA3_384, sym::hash_to_i16)         => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::I16)),
            (sym::SHA3_384, sym::hash_to_i32)         => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::I32)),
            (sym::SHA3_384, sym::hash_to_i64)         => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::I64)),
            (sym::SHA3_384, sym::hash_to_i128)        => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::I128)),
            (sym::SHA3_384, sym::hash_to_u8)          => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::U8)),
            (sym::SHA3_384, sym::hash_to_u16)         => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::U16)),
            (sym::SHA3_384, sym::hash_to_u32)         => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::U32)),
            (sym::SHA3_384, sym::hash_to_u64)         => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::U64)),
            (sym::SHA3_384, sym::hash_to_u128)        => Self::Hash(HashVariant::SHA3_384, false, Type::Integer(IntegerType::U128)),
            (sym::SHA3_384, sym::hash_to_scalar)      => Self::Hash(HashVariant::SHA3_384, false, Type::Scalar),
            (sym::SHA3_384, sym::hash_to_address_raw) => Self::Hash(HashVariant::SHA3_384, true, Type::Address),
            (sym::SHA3_384, sym::hash_to_field_raw)   => Self::Hash(HashVariant::SHA3_384, true, Type::Field),
            (sym::SHA3_384, sym::hash_to_group_raw)   => Self::Hash(HashVariant::SHA3_384, true, Type::Group),
            (sym::SHA3_384, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::I8)),
            (sym::SHA3_384, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::I16)),
            (sym::SHA3_384, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::I32)),
            (sym::SHA3_384, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::I64)),
            (sym::SHA3_384, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::I128)),
            (sym::SHA3_384, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::U8)),
            (sym::SHA3_384, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::U16)),
            (sym::SHA3_384, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::U32)),
            (sym::SHA3_384, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::U64)),
            (sym::SHA3_384, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::SHA3_384, true, Type::Integer(IntegerType::U128)),
            (sym::SHA3_384, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::SHA3_384, true, Type::Scalar),

            (sym::SHA3_512, sym::hash_to_address)     => Self::Hash(HashVariant::SHA3_512, false, Type::Address),
            (sym::SHA3_512, sym::hash_to_field)       => Self::Hash(HashVariant::SHA3_512, false, Type::Field),
            (sym::SHA3_512, sym::hash_to_group)       => Self::Hash(HashVariant::SHA3_512, false, Type::Group),
            (sym::SHA3_512, sym::hash_to_i8)          => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::I8)),
            (sym::SHA3_512, sym::hash_to_i16)         => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::I16)),
            (sym::SHA3_512, sym::hash_to_i32)         => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::I32)),
            (sym::SHA3_512, sym::hash_to_i64)         => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::I64)),
            (sym::SHA3_512, sym::hash_to_i128)        => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::I128)),
            (sym::SHA3_512, sym::hash_to_u8)          => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::U8)),
            (sym::SHA3_512, sym::hash_to_u16)         => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::U16)),
            (sym::SHA3_512, sym::hash_to_u32)         => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::U32)),
            (sym::SHA3_512, sym::hash_to_u64)         => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::U64)),
            (sym::SHA3_512, sym::hash_to_u128)        => Self::Hash(HashVariant::SHA3_512, false, Type::Integer(IntegerType::U128)),
            (sym::SHA3_512, sym::hash_to_scalar)      => Self::Hash(HashVariant::SHA3_512, false, Type::Scalar),
            (sym::SHA3_512, sym::hash_to_address_raw) => Self::Hash(HashVariant::SHA3_512, true, Type::Address),
            (sym::SHA3_512, sym::hash_to_field_raw)   => Self::Hash(HashVariant::SHA3_512, true, Type::Field),
            (sym::SHA3_512, sym::hash_to_group_raw)   => Self::Hash(HashVariant::SHA3_512, true, Type::Group),
            (sym::SHA3_512, sym::hash_to_i8_raw)      => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::I8)),
            (sym::SHA3_512, sym::hash_to_i16_raw)     => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::I16)),
            (sym::SHA3_512, sym::hash_to_i32_raw)     => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::I32)),
            (sym::SHA3_512, sym::hash_to_i64_raw)     => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::I64)),
            (sym::SHA3_512, sym::hash_to_i128_raw)    => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::I128)),
            (sym::SHA3_512, sym::hash_to_u8_raw)      => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::U8)),
            (sym::SHA3_512, sym::hash_to_u16_raw)     => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::U16)),
            (sym::SHA3_512, sym::hash_to_u32_raw)     => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::U32)),
            (sym::SHA3_512, sym::hash_to_u64_raw)     => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::U64)),
            (sym::SHA3_512, sym::hash_to_u128_raw)    => Self::Hash(HashVariant::SHA3_512, true, Type::Integer(IntegerType::U128)),
            (sym::SHA3_512, sym::hash_to_scalar_raw)  => Self::Hash(HashVariant::SHA3_512, true, Type::Scalar),

            (sym::ECDSA, sym::verify_keccak256)           => Self::ECDSAVerify(HashVariant::Keccak256, false, false),
            (sym::ECDSA, sym::verify_keccak256_raw)       => Self::ECDSAVerify(HashVariant::Keccak256, true, false),
            (sym::ECDSA, sym::verify_keccak256_eth)       => Self::ECDSAVerify(HashVariant::Keccak256, false, true),
            (sym::ECDSA, sym::verify_keccak256_eth_raw)   => Self::ECDSAVerify(HashVariant::Keccak256, true, true),
            (sym::ECDSA, sym::verify_keccak384)           => Self::ECDSAVerify(HashVariant::Keccak384, false, false),
            (sym::ECDSA, sym::verify_keccak384_raw)       => Self::ECDSAVerify(HashVariant::Keccak384, true, false),
            (sym::ECDSA, sym::verify_keccak384_eth)       => Self::ECDSAVerify(HashVariant::Keccak384, false, true),
            (sym::ECDSA, sym::verify_keccak384_eth_raw)   => Self::ECDSAVerify(HashVariant::Keccak384, true, true),
            (sym::ECDSA, sym::verify_keccak512)           => Self::ECDSAVerify(HashVariant::Keccak512, false, false),
            (sym::ECDSA, sym::verify_keccak512_raw)       => Self::ECDSAVerify(HashVariant::Keccak512, true, false),
            (sym::ECDSA, sym::verify_keccak512_eth)       => Self::ECDSAVerify(HashVariant::Keccak512, false, true),
            (sym::ECDSA, sym::verify_keccak512_eth_raw)   => Self::ECDSAVerify(HashVariant::Keccak512, true, true),
            (sym::ECDSA, sym::verify_sha3_256)            => Self::ECDSAVerify(HashVariant::SHA3_256, false, false),
            (sym::ECDSA, sym::verify_sha3_256_raw)        => Self::ECDSAVerify(HashVariant::SHA3_256, true, false),
            (sym::ECDSA, sym::verify_sha3_256_eth)        => Self::ECDSAVerify(HashVariant::SHA3_256, false, true),
            (sym::ECDSA, sym::verify_sha3_256_eth_raw)    => Self::ECDSAVerify(HashVariant::SHA3_256, true, true),
            (sym::ECDSA, sym::verify_sha3_384)            => Self::ECDSAVerify(HashVariant::SHA3_384, false, false),
            (sym::ECDSA, sym::verify_sha3_384_raw)        => Self::ECDSAVerify(HashVariant::SHA3_384, true, false),
            (sym::ECDSA, sym::verify_sha3_384_eth)        => Self::ECDSAVerify(HashVariant::SHA3_384, false, true),
            (sym::ECDSA, sym::verify_sha3_384_eth_raw)    => Self::ECDSAVerify(HashVariant::SHA3_384, true, true),
            (sym::ECDSA, sym::verify_sha3_512)            => Self::ECDSAVerify(HashVariant::SHA3_512, false, false),
            (sym::ECDSA, sym::verify_sha3_512_raw)        => Self::ECDSAVerify(HashVariant::SHA3_512, true, false),
            (sym::ECDSA, sym::verify_sha3_512_eth)        => Self::ECDSAVerify(HashVariant::SHA3_512, false, true),
            (sym::ECDSA, sym::verify_sha3_512_eth_raw)    => Self::ECDSAVerify(HashVariant::SHA3_512, true, true),

            (sym::Mapping, sym::get) => Self::MappingGet,
            (sym::Mapping, sym::get_or_use) => Self::MappingGetOrUse,
            (sym::Mapping, sym::set) => Self::MappingSet,
            (sym::Mapping, sym::remove) => Self::MappingRemove,
            (sym::Mapping, sym::contains) => Self::MappingContains,

            (sym::group, sym::to_x_coordinate) => Self::GroupToXCoordinate,
            (sym::group, sym::to_y_coordinate) => Self::GroupToYCoordinate,

            (sym::ProgramCore, sym::checksum) => Self::ProgramChecksum,
            (sym::ProgramCore, sym::edition) => Self::ProgramEdition,
            (sym::ProgramCore, sym::program_owner) => Self::ProgramOwner,

            (sym::signature, sym::verify) => Self::SignatureVerify(false),
            (sym::signature, sym::verify_raw) => Self::SignatureVerify(true),
            (sym::Future, sym::Await) => Self::FutureAwait,

            (sym::CheatCode, sym::print_mapping) => Self::CheatCodePrintMapping,
            (sym::CheatCode, sym::set_block_height) => Self::CheatCodeSetBlockHeight,
            _ => return None,
        })
    }

    /// Returns the number of arguments required by the instruction.
    pub fn num_args(&self) -> usize {
        match self {
            Self::ChaChaRand(_) => 0,
            Self::Commit(_, _) => 2,
            Self::Hash(_, _, _) => 2,
            Self::ECDSAVerify(_, _, _) => 3,

            Self::MappingGet => 2,
            Self::MappingGetOrUse => 3,
            Self::MappingSet => 3,
            Self::MappingRemove => 2,
            Self::MappingContains => 2,

            Self::GroupToXCoordinate => 1,
            Self::GroupToYCoordinate => 1,

            Self::SignatureVerify(_) => 3,
            Self::FutureAwait => 1,

            Self::ProgramChecksum => 1,
            Self::ProgramEdition => 1,
            Self::ProgramOwner => 1,
            Self::CheatCodePrintMapping => 1,
            Self::CheatCodeSetBlockHeight => 1,
        }
    }

    /// Returns whether or not this function is finalize command.
    pub fn is_finalize_command(&self) -> bool {
        match self {
            CoreFunction::FutureAwait
            | CoreFunction::ChaChaRand(_)
            | CoreFunction::ECDSAVerify(_, _, _)
            | CoreFunction::MappingGet
            | CoreFunction::MappingGetOrUse
            | CoreFunction::MappingSet
            | CoreFunction::MappingRemove
            | CoreFunction::MappingContains
            | CoreFunction::ProgramChecksum
            | CoreFunction::ProgramEdition
            | CoreFunction::ProgramOwner => true,
            CoreFunction::Commit(_, _)
            | CoreFunction::Hash(_, _, _)
            | CoreFunction::GroupToXCoordinate
            | CoreFunction::GroupToYCoordinate
            | CoreFunction::SignatureVerify(_)
            | CoreFunction::CheatCodePrintMapping
            | CoreFunction::CheatCodeSetBlockHeight => false,
        }
    }

    /// Returns the opcode for this core function.
    pub fn opcode(&self) -> String {
        match self {
            CoreFunction::ChaChaRand(_) => "rand.chacha".to_string(),
            CoreFunction::Commit(variant, _) => format!("commit.{variant}"),
            CoreFunction::Hash(variant, raw, _) => format!("hash.{variant}{}", if *raw { ".raw" } else { "" }),
            CoreFunction::ECDSAVerify(variant, raw, eth) => {
                format!("ecdsa.verify.{variant}{}{}", if *eth { ".eth" } else { "" }, if *raw { ".raw" } else { "" })
            }
            CoreFunction::MappingGet => "get".to_string(),
            CoreFunction::MappingGetOrUse => "get.or_use".to_string(),
            CoreFunction::MappingSet => "set".to_string(),
            CoreFunction::MappingRemove => "remove".to_string(),
            CoreFunction::MappingContains => "contains".to_string(),
            CoreFunction::GroupToXCoordinate => panic!("No opcode for GroupToXCoordinate"),
            CoreFunction::GroupToYCoordinate => panic!("No opcode for GroupToYCoordinate"),
            CoreFunction::SignatureVerify(raw) => format!("signature.verify{}", if *raw { ".raw" } else { "" }),
            CoreFunction::FutureAwait => "await".to_string(),
            CoreFunction::ProgramChecksum => panic!("No opcode for ProgramChecksum"),
            CoreFunction::ProgramEdition => panic!("No opcode for ProgramEdition"),
            CoreFunction::ProgramOwner => panic!("No opcode for ProgramOwner"),
            CoreFunction::CheatCodePrintMapping => panic!("No opcode for CheatCodePrintMapping"),
            CoreFunction::CheatCodeSetBlockHeight => panic!("No opcode for CheatCodeSetBlockHeight"),
        }
    }
}
