/*
namespace: Compile
expectation: Fail
*/

program test.aleo {

    transition one() -> u8 {
        return 1u8 + 1u8;
    }

    transition two() -> u8 {
        return 2u8 + 2u8;
    }

    transition three() -> u8 {
        return 3u8 + 3u8;
    }

    transition four() -> u8 {
        return 4u8 + 4u8;
    }

    transition five() -> u8 {
        return 5u8 + 5u8;
    }

    transition six() -> u8 {
        return 6u8 + 6u8;
    }

    transition seven() -> u8 {
        return 7u8 + 7u8;
    }

    transition eight() -> u8 {
        return 8u8 + 8u8;
    }

    transition nine() -> u8 {
        return 9u8 + 9u8;
    }

    transition ten() -> u8 {
        return 10u8 + 10u8;
    }

    transition eleven() -> u8 {
        return 11u8 + 11u8;
    }

    transition twelve() -> u8 {
        return 12u8 + 12u8;
    }

    transition thirteen() -> u8 {
        return 13u8 + 13u8;
    }

    transition fourteen() -> u8 {
        return 14u8 + 14u8;
    }

    transition fifteen() -> u8 {
        return 15u8 + 15u8;
    }

    transition sixteen() -> u8 {
        return 16u8 + 16u8;
    }
}
