#!/usr/bin/env bash

LEO_BIN=${1}

cd test_program1
echo "DEPLOYMENT 1"
${LEO_BIN} deploy -y --broadcast --twice --endpoint 'http://localhost:3030' --network testnet --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH

cd ../test_program2
echo "DEPLOYMENT 2"
${LEO_BIN} deploy -y --broadcast --twice --endpoint 'http://localhost:3030' --network testnet --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH

echo "EXECUTION"
${LEO_BIN} execute test_program2.aleo/main -y --broadcast --endpoint 'http://localhost:3030' --network testnet --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH
