/*
namespace: Bench
expectation: Pass
*/

@program
function main() -> u8 {
    return x191(0u32);
}

@program
function x0(val: u8) -> u8 { return val; }
@program
function x1(val: u8) -> u8 { return x0(val); }
@program
function x2(val: u8) -> u8 { return x1(val); }
@program
function x3(val: u8) -> u8 { return x2(val); }
@program
function x4(val: u8) -> u8 { return x3(val); }
@program
function x5(val: u8) -> u8 { return x4(val); }
@program
function x6(val: u8) -> u8 { return x5(val); }
@program
function x7(val: u8) -> u8 { return x6(val); }
@program
function x8(val: u8) -> u8 { return x7(val); }
@program
function x9(val: u8) -> u8 { return x8(val); }
@program
function x10(val: u8) -> u8 { return x9(val); }
@program
function x11(val: u8) -> u8 { return x10(val); }
@program
function x12(val: u8) -> u8 { return x11(val); }
@program
function x13(val: u8) -> u8 { return x12(val); }
@program
function x14(val: u8) -> u8 { return x13(val); }
@program
function x15(val: u8) -> u8 { return x14(val); }
@program
function x16(val: u8) -> u8 { return x15(val); }
@program
function x17(val: u8) -> u8 { return x16(val); }
@program
function x18(val: u8) -> u8 { return x17(val); }
@program
function x19(val: u8) -> u8 { return x18(val); }
@program
function x20(val: u8) -> u8 { return x19(val); }
@program
function x21(val: u8) -> u8 { return x20(val); }
@program
function x22(val: u8) -> u8 { return x21(val); }
@program
function x23(val: u8) -> u8 { return x22(val); }
@program
function x24(val: u8) -> u8 { return x23(val); }
@program
function x25(val: u8) -> u8 { return x24(val); }
@program
function x26(val: u8) -> u8 { return x25(val); }
@program
function x27(val: u8) -> u8 { return x26(val); }
@program
function x28(val: u8) -> u8 { return x27(val); }
@program
function x29(val: u8) -> u8 { return x28(val); }
@program
function x30(val: u8) -> u8 { return x29(val); }
@program
function x31(val: u8) -> u8 { return x30(val); }
@program
function x32(val: u8) -> u8 { return x31(val); }
@program
function x33(val: u8) -> u8 { return x32(val); }
@program
function x34(val: u8) -> u8 { return x33(val); }
@program
function x35(val: u8) -> u8 { return x34(val); }
@program
function x36(val: u8) -> u8 { return x35(val); }
@program
function x37(val: u8) -> u8 { return x36(val); }
@program
function x38(val: u8) -> u8 { return x37(val); }
@program
function x39(val: u8) -> u8 { return x38(val); }
@program
function x40(val: u8) -> u8 { return x39(val); }
@program
function x41(val: u8) -> u8 { return x40(val); }
@program
function x42(val: u8) -> u8 { return x41(val); }
@program
function x43(val: u8) -> u8 { return x42(val); }
@program
function x44(val: u8) -> u8 { return x43(val); }
@program
function x45(val: u8) -> u8 { return x44(val); }
@program
function x46(val: u8) -> u8 { return x45(val); }
@program
function x47(val: u8) -> u8 { return x46(val); }
@program
function x48(val: u8) -> u8 { return x47(val); }
@program
function x49(val: u8) -> u8 { return x48(val); }
@program
function x50(val: u8) -> u8 { return x49(val); }
@program
function x51(val: u8) -> u8 { return x50(val); }
@program
function x52(val: u8) -> u8 { return x51(val); }
@program
function x53(val: u8) -> u8 { return x52(val); }
@program
function x54(val: u8) -> u8 { return x53(val); }
@program
function x55(val: u8) -> u8 { return x54(val); }
@program
function x56(val: u8) -> u8 { return x55(val); }
@program
function x57(val: u8) -> u8 { return x56(val); }
@program
function x58(val: u8) -> u8 { return x57(val); }
@program
function x59(val: u8) -> u8 { return x58(val); }
@program
function x60(val: u8) -> u8 { return x59(val); }
@program
function x61(val: u8) -> u8 { return x60(val); }
@program
function x62(val: u8) -> u8 { return x61(val); }
@program
function x63(val: u8) -> u8 { return x62(val); }
@program
function x64(val: u8) -> u8 { return x63(val); }
@program
function x65(val: u8) -> u8 { return x64(val); }
@program
function x66(val: u8) -> u8 { return x65(val); }
@program
function x67(val: u8) -> u8 { return x66(val); }
@program
function x68(val: u8) -> u8 { return x67(val); }
@program
function x69(val: u8) -> u8 { return x68(val); }
@program
function x70(val: u8) -> u8 { return x69(val); }
@program
function x71(val: u8) -> u8 { return x70(val); }
@program
function x72(val: u8) -> u8 { return x71(val); }
@program
function x73(val: u8) -> u8 { return x72(val); }
@program
function x74(val: u8) -> u8 { return x73(val); }
@program
function x75(val: u8) -> u8 { return x74(val); }
@program
function x76(val: u8) -> u8 { return x75(val); }
@program
function x77(val: u8) -> u8 { return x76(val); }
@program
function x78(val: u8) -> u8 { return x77(val); }
@program
function x79(val: u8) -> u8 { return x78(val); }
@program
function x80(val: u8) -> u8 { return x79(val); }
@program
function x81(val: u8) -> u8 { return x80(val); }
@program
function x82(val: u8) -> u8 { return x81(val); }
@program
function x83(val: u8) -> u8 { return x82(val); }
@program
function x84(val: u8) -> u8 { return x83(val); }
@program
function x85(val: u8) -> u8 { return x84(val); }
@program
function x86(val: u8) -> u8 { return x85(val); }
@program
function x87(val: u8) -> u8 { return x86(val); }
@program
function x88(val: u8) -> u8 { return x87(val); }
@program
function x89(val: u8) -> u8 { return x88(val); }
@program
function x90(val: u8) -> u8 { return x89(val); }
@program
function x91(val: u8) -> u8 { return x90(val); }
@program
function x92(val: u8) -> u8 { return x91(val); }
@program
function x93(val: u8) -> u8 { return x92(val); }
@program
function x94(val: u8) -> u8 { return x93(val); }
@program
function x95(val: u8) -> u8 { return x94(val); }
@program
function x96(val: u8) -> u8 { return x95(val); }
@program
function x97(val: u8) -> u8 { return x96(val); }
@program
function x98(val: u8) -> u8 { return x97(val); }
@program
function x99(val: u8) -> u8 { return x98(val); }
@program
function x100(val: u8) -> u8 { return x99(val); }
@program
function x101(val: u8) -> u8 { return x100(val); }
@program
function x102(val: u8) -> u8 { return x101(val); }
@program
function x103(val: u8) -> u8 { return x102(val); }
@program
function x104(val: u8) -> u8 { return x103(val); }
@program
function x105(val: u8) -> u8 { return x104(val); }
@program
function x106(val: u8) -> u8 { return x105(val); }
@program
function x107(val: u8) -> u8 { return x106(val); }
@program
function x108(val: u8) -> u8 { return x107(val); }
@program
function x109(val: u8) -> u8 { return x108(val); }
@program
function x110(val: u8) -> u8 { return x109(val); }
@program
function x111(val: u8) -> u8 { return x110(val); }
@program
function x112(val: u8) -> u8 { return x111(val); }
@program
function x113(val: u8) -> u8 { return x112(val); }
@program
function x114(val: u8) -> u8 { return x113(val); }
@program
function x115(val: u8) -> u8 { return x114(val); }
@program
function x116(val: u8) -> u8 { return x115(val); }
@program
function x117(val: u8) -> u8 { return x116(val); }
@program
function x118(val: u8) -> u8 { return x117(val); }
@program
function x119(val: u8) -> u8 { return x118(val); }
@program
function x120(val: u8) -> u8 { return x119(val); }
@program
function x121(val: u8) -> u8 { return x120(val); }
@program
function x122(val: u8) -> u8 { return x121(val); }
@program
function x123(val: u8) -> u8 { return x122(val); }
@program
function x124(val: u8) -> u8 { return x123(val); }
@program
function x125(val: u8) -> u8 { return x124(val); }
@program
function x126(val: u8) -> u8 { return x125(val); }
@program
function x127(val: u8) -> u8 { return x126(val); }
@program
function x128(val: u8) -> u8 { return x127(val); }
@program
function x129(val: u8) -> u8 { return x128(val); }
@program
function x130(val: u8) -> u8 { return x129(val); }
@program
function x131(val: u8) -> u8 { return x130(val); }
@program
function x132(val: u8) -> u8 { return x131(val); }
@program
function x133(val: u8) -> u8 { return x132(val); }
@program
function x134(val: u8) -> u8 { return x133(val); }
@program
function x135(val: u8) -> u8 { return x134(val); }
@program
function x136(val: u8) -> u8 { return x135(val); }
@program
function x137(val: u8) -> u8 { return x136(val); }
@program
function x138(val: u8) -> u8 { return x137(val); }
@program
function x139(val: u8) -> u8 { return x138(val); }
@program
function x140(val: u8) -> u8 { return x139(val); }
@program
function x141(val: u8) -> u8 { return x140(val); }
@program
function x142(val: u8) -> u8 { return x141(val); }
@program
function x143(val: u8) -> u8 { return x142(val); }
@program
function x144(val: u8) -> u8 { return x143(val); }
@program
function x145(val: u8) -> u8 { return x144(val); }
@program
function x146(val: u8) -> u8 { return x145(val); }
@program
function x147(val: u8) -> u8 { return x146(val); }
@program
function x148(val: u8) -> u8 { return x147(val); }
@program
function x149(val: u8) -> u8 { return x148(val); }
@program
function x150(val: u8) -> u8 { return x149(val); }
@program
function x151(val: u8) -> u8 { return x150(val); }
@program
function x152(val: u8) -> u8 { return x151(val); }
@program
function x153(val: u8) -> u8 { return x152(val); }
@program
function x154(val: u8) -> u8 { return x153(val); }
@program
function x155(val: u8) -> u8 { return x154(val); }
@program
function x156(val: u8) -> u8 { return x155(val); }
@program
function x157(val: u8) -> u8 { return x156(val); }
@program
function x158(val: u8) -> u8 { return x157(val); }
@program
function x159(val: u8) -> u8 { return x158(val); }
@program
function x160(val: u8) -> u8 { return x159(val); }
@program
function x161(val: u8) -> u8 { return x160(val); }
@program
function x162(val: u8) -> u8 { return x161(val); }
@program
function x163(val: u8) -> u8 { return x162(val); }
@program
function x164(val: u8) -> u8 { return x163(val); }
@program
function x165(val: u8) -> u8 { return x164(val); }
@program
function x166(val: u8) -> u8 { return x165(val); }
@program
function x167(val: u8) -> u8 { return x166(val); }
@program
function x168(val: u8) -> u8 { return x167(val); }
@program
function x169(val: u8) -> u8 { return x168(val); }
@program
function x170(val: u8) -> u8 { return x169(val); }
@program
function x171(val: u8) -> u8 { return x170(val); }
@program
function x172(val: u8) -> u8 { return x171(val); }
@program
function x173(val: u8) -> u8 { return x172(val); }
@program
function x174(val: u8) -> u8 { return x173(val); }
@program
function x175(val: u8) -> u8 { return x174(val); }
@program
function x176(val: u8) -> u8 { return x175(val); }
@program
function x177(val: u8) -> u8 { return x176(val); }
@program
function x178(val: u8) -> u8 { return x177(val); }
@program
function x179(val: u8) -> u8 { return x178(val); }
@program
function x180(val: u8) -> u8 { return x179(val); }
@program
function x181(val: u8) -> u8 { return x180(val); }
@program
function x182(val: u8) -> u8 { return x181(val); }
@program
function x183(val: u8) -> u8 { return x182(val); }
@program
function x184(val: u8) -> u8 { return x183(val); }
@program
function x185(val: u8) -> u8 { return x184(val); }
@program
function x186(val: u8) -> u8 { return x185(val); }
@program
function x187(val: u8) -> u8 { return x186(val); }
@program
function x188(val: u8) -> u8 { return x187(val); }
@program
function x189(val: u8) -> u8 { return x188(val); }
@program
function x190(val: u8) -> u8 { return x189(val); }
@program
function x191(val: u8) -> u8 { return x190(val); }
