#!/usr/bin/env bash

LEO_BIN=${1}

echo "--- fmt program ---" | tee /dev/stderr
${LEO_BIN} fmt --check || true
${LEO_BIN} fmt
${LEO_BIN} fmt --check

echo "--- fmt library ---" | tee /dev/stderr
cd ugly_lib || exit 1
${LEO_BIN} fmt --check || true
${LEO_BIN} fmt
${LEO_BIN} fmt --check
