program test.aleo {
    mapping foo: u8 => u8;

    fn noop() -> Final {
        return final {
            foo.set(0u8, 0u8);
            foo.set(1u8, 1u8);
            foo.set(2u8, 2u8);
            foo.set(3u8, 3u8);
            foo.set(4u8, 4u8);
            foo.set(5u8, 5u8);
            foo.set(6u8, 6u8);
            foo.set(7u8, 7u8);
            foo.set(8u8, 8u8);
            foo.set(9u8, 9u8);
            foo.set(10u8, 10u8);
            foo.set(11u8, 11u8);
            foo.set(12u8, 12u8);
            foo.set(13u8, 13u8);
            foo.set(14u8, 14u8);
            foo.set(15u8, 15u8);
            foo.set(16u8, 16u8);
            foo.set(17u8, 17u8);
            foo.set(18u8, 18u8);
            foo.set(19u8, 19u8);
            foo.set(20u8, 20u8);
            foo.set(21u8, 21u8);
            foo.set(22u8, 22u8);
            foo.set(23u8, 23u8);
            foo.set(24u8, 24u8);
            foo.set(25u8, 25u8);
            foo.set(26u8, 26u8);
            foo.set(27u8, 27u8);
            foo.set(28u8, 28u8);
            foo.set(29u8, 29u8);
            foo.set(30u8, 30u8);
            foo.set(31u8, 31u8);
            foo.set(32u8, 32u8);
        };
    }
}
