#!/usr/bin/env bash

LEO_BIN=${1}
PRIVATE_KEY="APrivateKey1zkp2RWGDcde3efb89rjhME1VYA8QMxcxep5DShNBR6n8Yjh"
COMMON_OPTS="--disable-update-check --devnet --network testnet --endpoint http://localhost:3030 --private-key $PRIVATE_KEY --consensus-heights 0,1,2,3,4,5,6,7,8,9,10,11"

$LEO_BIN run --json-output main 1u32 2u32

$LEO_BIN test --json-output

$LEO_BIN synthesize --json-output --local test_json_program.aleo $COMMON_OPTS

$LEO_BIN deploy -y --json-output --broadcast $COMMON_OPTS

$LEO_BIN execute -y --json-output --broadcast main 1u32 2u32 $COMMON_OPTS

$LEO_BIN query --json-output program test_json_program.aleo $COMMON_OPTS

$LEO_BIN upgrade -y --json-output --broadcast $COMMON_OPTS
