#!/usr/bin/env bash

LEO_BIN=${1}

${LEO_BIN} --disable-update-check add --network credits.aleo

${LEO_BIN} --disable-update-check build

${LEO_BIN} --disable-update-check execute main 1u32 2u32 --network testnet --endpoint https://api.explorer.provable.com/v1 --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH --yes

${LEO_BIN} --disable-update-check execute main 1u32 2u32 --network testnet --endpoint http://localhost:3030 --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH --yes
