/*
namespace: Compile
expectation: Fail
*/

program test.aleo {

    transition one() -> u8 {
        return 1u8 + 1u8;
    }

    transition two() -> u8 {
        return 2u8 + 2u8;
    }

    transition three() -> u8 {
        return 3u8 + 3u8;
    }

    transition four() -> u8 {
        return 4u8 + 4u8;
    }

    transition five() -> u8 {
        return 5u8 + 5u8;
    }

    transition six() -> u8 {
        return 6u8 + 6u8;
    }

    transition seven() -> u8 {
        return 7u8 + 7u8;
    }

    transition eight() -> u8 {
        return 8u8 + 8u8;
    }

    transition nine() -> u8 {
        return 9u8 + 9u8;
    }

    transition ten() -> u8 {
        return 10u8 + 10u8;
    }

    transition eleven() -> u8 {
        return 11u8 + 11u8;
    }

    transition twelve() -> u8 {
        return 12u8 + 12u8;
    }

    transition thirteen() -> u8 {
        return 13u8 + 13u8;
    }

    transition fourteen() -> u8 {
        return 14u8 + 14u8;
    }

    transition fifteen() -> u8 {
        return 15u8 + 15u8;
    }

    transition sixteen() -> u8 {
        return 16u8 + 16u8;
    }

    transition seventeen() -> u8 {
        return 17u8 + 17u8;
    }

    transition eighteen() -> u8 {
        return 18u8 + 18u8;
    }

    transition nineteen() -> u8 {
        return 19u8 + 19u8;
    }

    transition twenty() -> u8 {
        return 20u8 + 20u8;
    }

    transition twenty_one() -> u8 {
        return 21u8 + 21u8;
    }

    transition twenty_two() -> u8 {
        return 22u8 + 22u8;
    }

    transition twenty_three() -> u8 {
        return 23u8 + 23u8;
    }

    transition twenty_four() -> u8 {
        return 24u8 + 24u8;
    }

    transition twenty_five() -> u8 {
        return 25u8 + 25u8;
    }

    transition twenty_six() -> u8 {
        return 26u8 + 26u8;
    }

    transition twenty_seven() -> u8 {
        return 27u8 + 27u8;
    }

    transition twenty_eight() -> u8 {
        return 28u8 + 28u8;
    }

    transition twenty_nine() -> u8 {
        return 29u8 + 29u8;
    }

    transition thirty() -> u8 {
        return 30u8 + 30u8;
    }

    transition thirty_one() -> u8 {
        return 31u8 + 31u8;
    }

    transition thirty_two() -> u8 {
        return 32u8 + 32u8;
    }
}
