
program test.aleo {

    fn one() -> u8 {
        return 1u8 + 1u8;
    }

    fn two() -> u8 {
        return 2u8 + 2u8;
    }

    fn three() -> u8 {
        return 3u8 + 3u8;
    }

    fn four() -> u8 {
        return 4u8 + 4u8;
    }

    fn five() -> u8 {
        return 5u8 + 5u8;
    }

    fn six() -> u8 {
        return 6u8 + 6u8;
    }

    fn seven() -> u8 {
        return 7u8 + 7u8;
    }

    fn eight() -> u8 {
        return 8u8 + 8u8;
    }

    fn nine() -> u8 {
        return 9u8 + 9u8;
    }

    fn ten() -> u8 {
        return 10u8 + 10u8;
    }

    fn eleven() -> u8 {
        return 11u8 + 11u8;
    }

    fn twelve() -> u8 {
        return 12u8 + 12u8;
    }

    fn thirteen() -> u8 {
        return 13u8 + 13u8;
    }

    fn fourteen() -> u8 {
        return 14u8 + 14u8;
    }

    fn fifteen() -> u8 {
        return 15u8 + 15u8;
    }

    fn sixteen() -> u8 {
        return 16u8 + 16u8;
    }

    fn seventeen() -> u8 {
        return 17u8 + 17u8;
    }

    fn eighteen() -> u8 {
        return 18u8 + 18u8;
    }

    fn nineteen() -> u8 {
        return 19u8 + 19u8;
    }

    fn twenty() -> u8 {
        return 20u8 + 20u8;
    }

    fn twenty_one() -> u8 {
        return 21u8 + 21u8;
    }

    fn twenty_two() -> u8 {
        return 22u8 + 22u8;
    }

    fn twenty_three() -> u8 {
        return 23u8 + 23u8;
    }

    fn twenty_four() -> u8 {
        return 24u8 + 24u8;
    }

    fn twenty_five() -> u8 {
        return 25u8 + 25u8;
    }

    fn twenty_six() -> u8 {
        return 26u8 + 26u8;
    }

    fn twenty_seven() -> u8 {
        return 27u8 + 27u8;
    }

    fn twenty_eight() -> u8 {
        return 28u8 + 28u8;
    }

    fn twenty_nine() -> u8 {
        return 29u8 + 29u8;
    }

    fn thirty() -> u8 {
        return 30u8 + 30u8;
    }

    fn thirty_one() -> u8 {
        return 31u8 + 31u8;
    }

    fn thirty_two() -> u8 {
        return 32u8 + 32u8;
    }
}
