program labels.aleo {
    fn foo() {}
}
struct Foo0 {
    x: u32,
    x: u32
}

struct Foo1 {
    x: u32,

    x: u32
}

struct Foo2 {
    x: u32,


    x: u32
}

struct Foo3 {
    x
        : 
            u32,
    x: u32
}

struct Foo4 {
    x
        : 
            u32,

    x: u32
}

struct Foo5 {
    x
        : 
            u32,


    x: u32
}

struct Foo6 {
    x
        : 
            u32,
    x
         : 
                u32
}

struct Foo7 {
    x
        : 
            u32,



    x
             : 
                 u32
}

