program labels.aleo {
    fn foo() {}

    @noupgrade
    constructor() {}
}

export struct Foo0 {
    x: u32,
    x: u32,
}

export struct Foo1 {
    x: u32,
    x: u32,
}

export struct Foo2 {
    x: u32,
    x: u32,
}

export struct Foo3 {
    x: u32,
    x: u32,
}

export struct Foo4 {
    x: u32,
    x: u32,
}

export struct Foo5 {
    x: u32,
    x: u32,
}

export struct Foo6 {
    x: u32,
    x: u32,
}

export struct Foo7 {
    x: u32,
    x: u32,
}
