/*
namespace: ParseExpression
expectation: Pass
*/

(+, _)group

(_, -)group

(+, -)group

(-, +)group

(+, +)group

(-, -)group

(_, _)group


(123,-456)group

(-123,456)group

(-123,456)group

(123, _)group

(123, -)group

(123, -)group

(123, +)group

(123, +)group

(123, -)group

(123, _)group

(+, 345)group

(_, 345)group

(+, 345)group

(-, 345)group

(+, 345)group

(-, 345)group

(_, 345)group


(123, 456)group

(123, 456)group

(123, 456)group

(123, 456)group

(123, 456)group

(123, 456)group

(123, 456)group

1group

-1group