/*
namespace: Compile
expectation: Fail
*/

program test.aleo {

    mapping one: field => field;
    mapping two: field => field;
    mapping three: field => field;
    mapping four: field => field;
    mapping five: field => field;
    mapping six: field => field;
    mapping seven: field => field;
    mapping eight: field => field;
    mapping nine: field => field;
    mapping ten: field => field;
    mapping eleven: field => field;
    mapping twelve: field => field;
    mapping thirteen: field => field;
    mapping fourteen: field => field;
    mapping fifteen: field => field;
    mapping sixteen: field => field;
    mapping seventeen: field => field;
    mapping eighteen: field => field;
    mapping nineteen: field => field;
    mapping twenty: field => field;
    mapping twentyone: field => field;
    mapping twentytwo: field => field;
    mapping twentythree: field => field;
    mapping twentyfour: field => field;
    mapping twentyfive: field => field;
    mapping twentysix: field => field;
    mapping twentyseven: field => field;
    mapping twentyeight: field => field;
    mapping twentynine: field => field;
    mapping thirty: field => field;
    mapping thirtyone: field => field;
    mapping thirtytwo: field => field;

    transition foo() -> u8 {
        return 1u8 + 1u8;
    }
}
