#!/usr/bin/env bash

LEO_BIN=${1}
COMMON_OPTS="--disable-update-check"

# Field encodings:
#   extra_prog -> 488459582523545069320293field
#   aleo       -> 1868917857field
#   dbl        -> 7103076field
PROG="488459582523545069320293field"
NET="1868917857field"
FUNC="7103076field"
INPUT="7u64"

echo "--- run WITHOUT --with should fail ---"
${LEO_BIN} ${COMMON_OPTS} run main ${PROG} ${NET} ${FUNC} ${INPUT} 2>&1 || true

echo "--- run WITH --with should succeed ---"
${LEO_BIN} ${COMMON_OPTS} run main ${PROG} ${NET} ${FUNC} ${INPUT} --with ./extra_prog.aleo

exit 0
