program test.aleo{
	fn main(  public x  :  u8  ){

let a  :u8  =  1u8;
                    let b:u16=2u16;
  let c :u32  =
      3u32;

        let d:   u64   =4u64;
	    let e  :  u128  =  5u128;

let f:i8=  -1i8;
            let g:i16  =-2i16;
        let h  :  i32=
            -3i32;


	let i:i64
        =-4i64;
                let j  :i128  =  -5i128;

    let k :  field  =  1field;
let l  :scalar=1scalar;
        let m:bool
      =true;
                    let n  :  bool  =  false;

let o:address  =aleo1qnr4dkkvkgfqph0vzc3y6z2eu975wnpz2925ntjccd5cfqxtyu8s7pyjh9;

	}
}
