/*
namespace: Parse
expectation: Fail
*/

circuit ;

circuit .

circuit import

circuit ,

circuit *

circuit +

circuit -

circuit /

circuit [

circuit ]

circuit {

circuit }

circuit (

circuit )

circuit :

circuit ::

circuit ?

circuit _

circuit =

circuit ==

circuit !

circuit !=

circuit >

circuit >=

circuit <

circuit <=

circuit >

circuit ..

circuit as

circuit console

circuit const

circuit let

circuit for

circuit if

circuit else

circuit i8

circuit i16

circuit i32

circuit i64

circuit i128

circuit u8

circuit u16

circuit u32

circuit u64

circuit u128

circuit &

circuit return

circuit self

circuit Self

circuit true

circuit false

circuit 0