/*
namespace: Parse
expectation: Fail
*/
struct import

program test.aleo {    
    struct ;
    
    struct .
    
    
    struct ,
    
    struct *
    
    struct +
    
    struct -
    
    struct /
    
    struct [
    
    struct ]
    
    struct {
    
    struct }
    
    struct (
    
    struct )
    
    struct :
    
    struct ::
    
    struct ?
    
    struct _
    
    struct =
    
    struct ==
    
    struct !
    
    struct !=
    
    struct >
    
    struct >=
    
    struct <
    
    struct <=
    
    struct >
    
    struct ..
    
    struct as
    
    struct console
    
    struct const
    
    struct let
    
    struct for
    
    struct if
    
    struct else
    
    struct i8
    
    struct i16
    
    struct i32
    
    struct i64
    
    struct i128
    
    struct u8
    
    struct u16
    
    struct u32
    
    struct u64
    
    struct u128
    
    struct &
    
    struct return
    
    struct self
    
    struct Self
    
    struct true
    
    struct false
    
    struct 0}
