/*
namespace: ParseExpression
expectation: Fail
*/

if 10 ; {}
if 10 . {}
if 10 import {}
if 10 , {}
if 10 * {}
if 10 + {}
if 10 - {}
if 10 / {}
if 10 [ {}
if 10 ] {}
if 10 { {}
if 10 } {}
if 10 ( {}
if 10 ) {}
if 10 : {}
if 10 :: {}
if 10 ? {}
if 10 _ {}
if 10 = {}
if 10 == {}
if 10 ! {}
if 10 != {}
if 10 > {}
if 10 >= {}
if 10 < {}
if 10 <= {}
if 10 > {}
if 10 .. {}
if 10 as {}
if 10 console {}
if 10 const {}
if 10 let {}
if 10 for {}
if 10 if {}
if 10 else {}
if 10 i8 {}
if 10 i16 {}
if 10 i32 {}
if 10 i64 {}
if 10 i128 {}
if 10 u8 {}
if 10 u16 {}
if 10 u32 {}
if 10 u64 {}
if 10 u128 {}
if 10 & {}
if 10 return {}
if 10 self {}
if 10 Self {}
if 10 true {}
if 10 false {}
if 10 0 {}