/*
namespace: ParseStatement
expectation: Fail
*/

x::;

x::.

x::import

x::,

x::*

x::+

x::-

x::/

x::[

x::]

x::{

x::}

x::(

x::)

x:::

x::::

x::?

x::_

x::=

x::==

x::!

x::!=

x::>

x::>=

x::<

x::<=

x::>

x::..

x::as

x::console

x::const

x::let

x::for

x::if

x::else

x::i8

x::i16

x::i32

x::i64

x::i128

x::u8

x::u16

x::u32

x::u64

x::u128

x::&

x::return

x::self

x::Self

x::true

x::false

x::0
