/*
namespace: ParseStatement
expectation: Pass
*/

let x = a . b;

let x = a :: b;

let x = a == b;

let x = a != b;

let x = a > b;

let x = a >= b;

let x = a < b;

let x = a <= b;

let x = a > b;

let x = a as b;

ximport=b;

x_=b;

x==b;

x!=b;

x>=b;

x<=b;

x>=b;

xas=b;

xconsole=b;

xconst=b;

xlet=b;

xfor=b;

xif=b;

xelse=b;

xi8=b;

xi16=b;

xi32=b;

xi64=b;

xi128=b;

xu8=b;

xu16=b;

xu32=b;

xu64=b;

xu128=b;

xreturn=b;

xself=b;

xSelf=b;

xtrue=b;

xfalse=b;

x0=b;
