/*
namespace: ParseStatement
expectation: Fail
*/

let x = a;;
let x = a.;
let x = aimport;
let x = a,;
let x = a[;
let x = a];
let x = a{;
let x = a};
let x = a);
let x = a:;
let x = a?;
let x = a_;
let x = a=;
let x = a==;
let x = a!;
let x = a!=;
let x = a>;
let x = a>=;
let x = a<;
let x = a<=;
let x = a>;
let x = a..;
let x = aas;
let x = aconsole;
let x = aconst;
let x = alet;
let x = afor;
let x = aif;
let x = aelse;
let x = ai8;
let x = ai16;
let x = ai32;
let x = ai64;
let x = ai128;
let x = au8;
let x = au16;
let x = au32;
let x = au64;
let x = au128;
let x = a&;
let x = areturn;
let x = aself;
let x = aSelf;
let x = atrue;
let x = afalse;
let x = a0;