circuit address {
    function to_bits(self) -> [bool; 8] {
        return [false; 8];
    }

    function from_bits(bits: [bool; 8]) -> address {
        return aleo1qnr4dkkvkgfqph0vzc3y6z2eu975wnpz2925ntjccd5cfqxtyu8sta57j8;
    }

    function to_bytes(self) -> [u8; 8] {
        return [0u8; 8];
    }

    function from_bytes(bytes: [u8; 8]) -> address {
        return aleo1qnr4dkkvkgfqph0vzc3y6z2eu975wnpz2925ntjccd5cfqxtyu8sta57j8;
    }
}