/*
namespace: Input
expectation: Fail
*/

[main]
const public a: bool  = true;                 
const public b: u8    = 2;                    
const public c: field = 0;                    
const public d: group = (0, 1)group;          
const public e: address = aleo1qnr4dkkvkgfqph0vzc3y6z2eu975wnpz2925ntjccd5cfqxtyu8sta57j8;

[registers]
r0: bool  = true;                 
r1: u8    = 2;                    
r2: field = 0;                    
r3: group = (0, 1)group;          
r4: address = aleo1qnr4dkkvkgfqph0vzc3y6z2eu975wnpz2925ntjccd5cfqxtyu8sta57j8;

