#!/usr/bin/env bash

LEO_BIN=${1}
PRIVATE_KEY="APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH"
COMMON_OPTS="--disable-update-check --broadcast --network testnet --endpoint http://localhost:${LEO_DEVNODE_PORT:-3030} --private-key $PRIVATE_KEY --consensus-heights 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18"
ALEO_FILE="./build/some_sample_leo_program/some_sample_leo_program.aleo"

$LEO_BIN build --disable-update-check --network testnet --endpoint http://localhost:${LEO_DEVNODE_PORT:-3030}
$LEO_BIN --path $ALEO_FILE deploy -y $COMMON_OPTS
$LEO_BIN --path $ALEO_FILE execute -y main 1u32 2u32 $COMMON_OPTS
