#!/usr/bin/env bash

LEO_BIN=${1}

echo "=== simple.aleo ==="
${LEO_BIN} --disable-update-check abi simple.aleo

echo ""
echo "=== comprehensive.aleo ==="
${LEO_BIN} --disable-update-check abi comprehensive.aleo
