name: Mainnet Crates Docs
on:
  push:
    branches:
      - mainnet

jobs:
  build-crates-docs:
    name: Build Crates Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          ref: mainnet

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Set up rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Build Cargo Docs
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
          RUSTC_BOOTSTRAP: "1"
        run: |
          cargo doc --no-deps --document-private-items --workspace
          rm -rf ./tests

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
