/*
namespace: ParseExpression
expectation: Fail
*/

"test" ~

u32 ~

1 ~

true ~

false ~

aleo13jgjyzhzhvrqecjct7scsjrfsfn09j9vryung8mfykt5502p75rsx7l9lr ~

'h' ~

@test

!1 ~

&&

||

==

!=

<

<=

>

>=

+

-

*

**

/

=

+=

-=

*=

/=

**=

(

)

[

]

{

}

,

.

..

...

;

:

h::

?

->

_

u8 ~

u16 ~

u32 ~

u64 ~

u128 ~

i8 ~

i16 ~

i32 ~

i64 ~

i128 ~

field ~

group ~

bool ~

address ~

char ~

input ~

console

constant

else

for

function

if

in

let

&

return
